const actions = {
  SET_STATE: 'customer-list/SET_STATE',
  CLEAN_UP: 'customer-list/CLEAN_UP',

  LOAD_CUSTOMER_LIST: 'customer-list/LOAD_CUSTOMER_LIST',
  EXPORT_CUSTOMER_LIST: 'customer-list/EXPORT_CUSTOMER_LIST',
  UPDATE_RESET_PASSWORD_CUSTOMER: 'customer-list/UPDATE_RESET_PASSWORD_CUSTOMER',

  LOAD_EDIT_CUSTOMER: 'customer-list/LOAD_EDIT_CUSTOMER',
  LOAD_UPLINE_CUSTOMER: 'customer-list/LOAD_UPLINE_CUSTOMER',
  UPDATE_EDIT_CUSTOMER: 'customer-list/UPDATE_EDIT_CUSTOMER',

  LOAD_LIMIT_PROFILE: 'customer-list/LOAD_LIMIT_PROFILE',
  LOAD_CUSTOMER_BET_LIMIT: 'customer-list/LOAD_CUSTOMER_BET_LIMIT',
  LOAD_CUSTOMER_BET_LIMIT_BY_SPORT: 'customer-list/LOAD_CUSTOMER_BET_LIMIT_BY_SPORT',
  UPDATE_CUSTOMER_BET_LIMIT: 'customer-list/UPDATE_CUSTOMER_BET_LIMIT',
  UPDATE_CUSTOMER_BET_LIMIT_BY_SPORT: 'customer-list/UPDATE_CUSTOMER_BET_LIMIT_BY_SPORT',

  LOAD_BET_LIMIT_LOG: 'customer-list/LOAD_BET_LIMIT_LOG',

  LOAD_VIP_LOG: 'customer-list/LOAD_VIP_LOG',

  LOAD_CUSTOMER_DELAY_BET: 'customer-list/LOAD_CUSTOMER_DELAY_BET',
  UPDATE_CUSTOMER_DELAY_BET: 'customer-list/UPDATE_CUSTOMER_DELAY_BET',
}

export default actions
