const actions = {
  SET_STATE: 'sisActionLog/SET_STATE',

  LOAD_ACTION_LOG: 'sisActionLog/LOAD_ACTION_LOG',
  LOAD_ACTION_LOG_DETAIL: 'sisActionLog/LOAD_ACTION_LOG_DETAIL',
  LOAD_MARKET: 'sisActionLog/LOAD_MARKET',
  LOAD_MARKET_LOG: 'sisActionLog/LOAD_MARKET_LOG',
  LOAD_MATCH_LIST: 'sisActionLog/LOAD_MATCH_LIST',

  CLEAN_UP_ACTION_LOG: 'sisActionLog/CLEAN_UP_ACTION_LOG',
  CLEAN_UP_ACTION_LOG_DETAIL: 'sisActionLog/CLEAN_UP_ACTION_LOG_DETAIL',
  CLEAN_UP_MARKET: 'sisActionLog/CLEAN_UP_MARKET',
  CLEAN_UP_MARKET_LOG: 'sisActionLog/CLEAN_UP_MARKET_LOG',
  CLEAN_UP_MATCH_LIST: 'sisActionLog/CLEAN_UP_MATCH_LIST',
}

export default actions
