const actions = {
  SET_STATE: 'mo5/SET_STATE',
  CLEAN_UP: 'mo5/CLEAN_UP',
  CLEAN_UP_OGT_PAUSE_STATUS: 'mo5/CLEAN_UP_OGT_PAUSE_STATUS',

  GET_OGT_PAUSE_STATUS: 'mo5/GET_OGT_PAUSE_STATUS',
  GET_ALL_OGT_PAUSE_STATUS: 'mo5/GET_ALL_OGT_PAUSE_STATUS',
  ADD_CACHE: 'mo5/ADD_CACHE',
  SWAP_FAVOURITE: 'mo5/SWAP_FAVOURITE',
  UPDATE_ZERO_ODDS: 'mo5/UPDATE_ZERO_ODDS',
  MOVE_HANDICAP: 'mo5/MOVE_HANDICAP',
  CHANGE_HANDICAP: 'mo5/CHANGE_HANDICAP',
  SWAP_HANDICAP: 'mo5/SWAP_HANDICAP',
  CHANGE_ODDS: 'mo5/CHANGE_ODDS',
  CHANGE_ODDS_EURO: 'mo5/CHANGE_ODDS_EURO',
  CHANGE_ODDS_CSLIVE: 'mo5/CHANGE_ODDS_CSLIVE',
  CHANGE_ODDS_1X2: 'mo5/CHANGE_ODDS_1X2',
  SWAP_ODDS: 'mo5/SWAP_ODDS',
  MOVE_ODDS: 'mo5/MOVE_ODDS',
  CHANGE_LOD: 'mo5/CHANGE_LOD',
  CHANGE_SPREAD: 'mo5/CHANGE_SPREAD',
  CHANGE_AUTO_CALC_ODDS_1X2: 'mo5/CHANGE_AUTO_CALC_ODDS_1X2',
  CHANGE_LDIFF: 'mo5/CHANGE_LDIFF',
  CHANGE_LOCK_1X2: 'mo5/CHANGE_LOCK_1X2',

  PAUSE_RESUME_CHOICE: 'mo5/PAUSE_RESUME_CHOICE',
  PAUSE_RESUME_SUB_MATCH_CS: 'mo5/UPDATE_PAUSE_RESUME_SUB_MATCH_CS',
  PAUSE_RESUME_SUB_MATCH: 'mo5/UPDATE_PAUSE_RESUME_SUB_MATCH',
  PAUSE_RESUME_MATCH: 'mo5/PAUSE_RESUME_MATCH',
  PAUSE_RESUME_ALL: 'mo5/UPDATE_PAUSE_RESUME_ALL',
  OPEN_CLOSE_CHOICE: 'mo5/OPEN_CLOSE_CHOICE',
  OPEN_CLOSE_SUB_MATCH_CS: 'mo5/OPEN_CLOSE_SUB_MATCH_CS',
  OPEN_CLOSE_SUB_MATCH: 'mo5/OPEN_CLOSE_SUB_MATCH',
  OPEN_CLOSE_MATCH: 'mo5/OPEN_CLOSE_MATCH',
  FOLLOW_LEECH_SUB_MATCH: 'mo5/FOLLOW_LEECH_SUB_MATCH',
  UPDATE_LEECH_ASSIGN: 'mo5/UPDATE_LEECH_ASSIGN',

  // ui
  SET_NOTIFICATION: 'mo5/SET_NOTIFICATION',
}

export default actions
