const actions = {
  SET_STATE: 'team/SET_STATE',
  CLEAN_UP: 'team/CLEAN_UP',
  LOAD: 'team/LOAD',
  LOAD_DETAIL: 'team/LOAD_DETAIL',
  UPDATE: 'team/UPDATE',
  CREATE: 'team/CREATE',
  UPDATE_COUNTRY: 'team/UPDATE_COUNTRY',
  DELETE: 'team/DELETE',
  LOAD_SELECT_IN_ADDMATCH: 'team/LOAD_SELECT_IN_ADDMATCH',
  LOAD_SELECT_IN_STANDINGS: 'team/LOAD_SELECT_IN_STANDINGS',
  LOAD_SELECT_IN_KNOCKOUTS: 'team/LOAD_SELECT_IN_KNOCKOUTS',
  LOAD_SELECT_IN_OUTRIGHT: 'team/LOAD_SELECT_IN_OUTRIGHT',
  LOAD_SELECT_IN_MAPPING_TEAM: 'team/LOAD_SELECT_IN_MAPPING_TEAM',
  LOAD_SELECT_IN_MAPPING_TEAM_RB: 'team/LOAD_SELECT_IN_MAPPING_TEAM_RB',
}

export default actions
