package model

type AcceptRejectedTicket struct {
	Username                 string  `json:"username" db:"Username"`
	BetID                    int     `json:"bet_id" db:"Bet_ID"`
	BetType                  string  `json:"bet_type" db:"Bet_Type"`
	PendingBetID             int     `json:"pending_bet_id" db:"Pending_Bet_ID"`
	BetDate                  string  `json:"bet_date" db:"Bet_Date"`
	RejectDate               string  `json:"reject_date" db:"Reject_Date"`
	GameType                 int     `json:"game_type" db:"GameType"`
	BetLiveStatus            string  `json:"bet_live_status" db:"Bet_Live_Status"`
	MatchID                  int     `json:"match_id" db:"Match_ID"`
	ParlayGameType           int     `json:"parlay_game_type" db:"Parlay_GameType"`
	SportName                string  `json:"sport_name" db:"Sport_Name"`
	LeagueName               string  `json:"league_name" db:"League_Name"`
	HomeName                 string  `json:"home_name" db:"Home_Name"`
	AwayName                 string  `json:"away_name" db:"Away_Name"`
	BetChoice                string  `json:"bet_choice" db:"Bet_Choice"`
	Odds                     float64 `json:"odds" db:"Odds"`
	Handicap                 float64 `json:"handicap" db:"Handicap"`
	BetFavStatus             int     `json:"bet_fav_status" db:"Bet_Fav_Status"`
	BetNeutralStatus         string  `json:"bet_neutral_status" db:"Bet_Neutral_Status"`
	BetCommision             int     `json:"bet_commision" db:"Bet_Commision"`
	BetScoreHome             int     `json:"bet_score_home" db:"Bet_ScoreHome"`
	BetScoreAway             int     `json:"bet_score_away" db:"Bet_ScoreAway"`
	HTScoreStatus            string  `json:"ht_score_status" db:"HT_Score_Status"`
	FTScoreStatus            string  `json:"ft_score_status" db:"FT_Score_Status"`
	HTHome                   int     `json:"ht_home" db:"HT_Home"`
	HTAway                   int     `json:"ht_away" db:"HT_Away"`
	FSHome                   int     `json:"fs_home" db:"FS_Home"`
	FSAway                   int     `json:"fs_away" db:"FS_Away"`
	Currency                 string  `json:"currency" db:"Currency"`
	BetAmount                float64 `json:"bet_amount" db:"Bet_Amount"`
	BetAmountRMB             float64 `json:"bet_amount_rmb" db:"Bet_Amount_RMB"`
	WinLossAmount            float64 `json:"win_loss_amount" db:"WinLoss_Amount"`
	WinLossAmountRMB         float64 `json:"win_loss_amount_rmb" db:"WinLoss_Amount_RMB"`
	WinLossStatus            string  `json:"win_loss_status" db:"WinLoss_Status"`
	VoidID                   int     `json:"void_id" db:"Void_ID"`
	VoidUser                 string  `json:"void_user" db:"Void_User"`
	VoidDesc                 string  `json:"void_desc" db:"Void_Desc"`
	IP                       string  `json:"ip" db:"IP"`
	IsRejectedBet            string  `json:"is_rejected_bet" db:"Is_Rejected_Bet"`
	IsPostedBet              string  `json:"is_posted_bet" db:"Is_Posted_Bet"`
	IsProcessedBet           string  `json:"is_processed_bet" db:"Is_Processed_Bet"`
	ParlayCombination        int     `json:"parlay_combination" db:"Parlay_Combination"`
	ParlayMatchVoidID        string  `json:"parlay_match_void_id" db:"Parlay_Match_Void_ID"`
	ParlayMatchVoidDesc      string  `json:"parlay_match_void_desc" db:"Parlay_Match_Void_Desc"`
	ParlayMatchWinlossStatus string  `json:"parlay_match_winloss_status" db:"Parlay_Match_Winloss_Status"`
}
