package model

import "github.com/guregu/null"

type BetEnquiry struct {
	Username                   string      `json:"username" db:"UserName"`
	VIPCode                    string      `json:"vip_code" db:"VIPCode"`
	BetID                      int         `json:"bet_id" db:"Bet_ID"`
	BetType                    string      `json:"bet_type" db:"Bet_Type"`
	PendingBetID               int         `json:"pending_bet_id" db:"Pending_Bet_ID"`
	BetDate                    string      `json:"bet_date" db:"Bet_Date"`
	AcceptPendingDate          string      `json:"accept_pending_date" db:"Accept_Pending_Date"`
	GameType                   int         `json:"game_type" db:"GameType"`
	BetLiveStatus              string      `json:"bet_live_status" db:"Bet_Live_Status"`
	MatchID                    int         `json:"match_id" db:"Match_ID"`
	ParlayGameType             int         `json:"parlay_game_type" db:"Parlay_GameType"`
	LeagueName                 string      `json:"league_name" db:"League_Name"`
	SportName                  string      `json:"sport_name" db:"Sport_Name"`
	HomeName                   string      `json:"home_name" db:"Home_Name"`
	AwayName                   string      `json:"away_name" db:"Away_Name"`
	BetChoice                  string      `json:"bet_choice" db:"Bet_Choice"`
	Odds                       float64     `json:"odds" db:"Odds"`
	OddsType                   int         `json:"odds_type" db:"OddsType"`
	Handicap                   float64     `json:"handicap" db:"Handicap"`
	BetFavStatus               int         `json:"bet_fav_status" db:"Bet_Fav_Status"`
	BetNeutralStatus           null.String `json:"bet_neutral_status" db:"Bet_Neutral_Status"`
	BetCommision               float64     `json:"bet_commision" db:"Bet_Commision"`
	BetScoreHome               int         `json:"bet_score_home" db:"Bet_Score_Home"`
	BetScoreAway               int         `json:"bet_score_away" db:"Bet_Score_Away"`
	HTScoreStatus              null.String `json:"ht_score_status" db:"HT_Score_Status"`
	FTScoreStatus              null.String `json:"ft_score_status" db:"FT_Score_Status"`
	FGLGScoreStatus            null.String `json:"fglg_score_status" db:"FGLG_Score_Status"`
	HTHome                     null.Int    `json:"ht_home" db:"HT_Home"`
	HTAway                     null.Int    `json:"ht_away" db:"HT_Away"`
	FSHome                     null.Int    `json:"fs_home" db:"FS_Home"`
	FSAway                     null.Int    `json:"fs_away" db:"FS_Away"`
	FGTeam                     null.Int    `json:"fg_team" db:"FG_Team"`
	LGTeam                     null.Int    `json:"lg_team" db:"LG_Team"`
	Currency                   string      `json:"currency" db:"Currency"`
	BetAmount                  float64     `json:"bet_amount" db:"Bet_Amount"`
	BetAmountRMB               float64     `json:"bet_amount_rmb" db:"Bet_Amount_RMB"`
	WinLossAmount              float64     `json:"winloss_amount" db:"WinLoss_Amount"`
	WinLossAmountRMB           float64     `json:"winloss_amount_rmb" db:"WinLoss_Amount_RMB"`
	WinLossStatus              string      `json:"winloss_status" db:"WinLoss_Status"`
	VoidID                     string      `json:"void_id" db:"Void_ID"`
	VoidUser                   string      `json:"void_user" db:"Void_User"`
	VoidDesc                   string      `json:"void_desc" db:"Void_Desc"`
	IP                         string      `json:"ip" db:"IP"`
	IsRejectedBet              string      `json:"is_rejected_bet" db:"Is_Rejected_Bet"`
	IsPostedbet                string      `json:"is_posted_bet" db:"Is_Posted_Bet"`
	IsProcessedBet             string      `json:"is_processed_bet" db:"Is_Processed_Bet"`
	IsProcessedFS              string      `json:"is_processed_fs" db:"Is_Processed_FS"`
	IsProcessedHS              string      `json:"is_processed_hs" db:"Is_Processed_HS"`
	IsProcessedFGLG            string      `json:"is_processed_fglg" db:"Is_Processed_FGLG"`
	ParlayCombination          int         `json:"parlay_combination" db:"Parlay_Combination"`
	ParlayMatchVoidID          string      `json:"parlay_match_void_id" db:"Parlay_Match_Void_ID"`
	ParlayMatchVoidDescription string      `json:"parlay_match_void_description" db:"Parlay_Match_Void_Desc"`
	ParlayMatchWinLossStatus   string      `json:"parlay_match_winloss_status" db:"Parlay_Match_WinLoss_Status"`
	BetLoss                    float64     `json:"bet_loss" db:"Bet_Loss"`
	JWL                        float64     `json:"jwl" db:"JWL"`
	OutrightTeamWinner         string      `json:"outright_team_winner" db:"Outright_Team_Winner"`
	Folds                      int         `json:"folds" db:"Folds"`
	Tickets                    int         `json:"tickets" db:"Tickets"`
	StatusTicket               int         `json:"status_ticket" db:"StatusTicket"`
	ParlayLiveStatus           string      `json:"parlay_live_status" db:"Parlay_Live_Status"`
	UserAdminBuyBack           string      `json:"user_admin_buy_back" db:"UserAdminBuyBack"`
	Company                    null.String `json:"company" db:"Company"`
	SportID                    int         `json:"sport_id" db:"Sport_ID"`
	AOSExclude                 null.String `json:"aos_exclude" db:"AOSExclude"`
	EarlySettlementID          string      `json:"early_settlement_id" db:"EarlySettlementID"`
	BetBuilderMarket           string      `json:"bet_builder_market" db:"BetBuilderMarket"`
	LotteryLeagueName          string      `json:"lottery_league_name" db:"LotteryLeagueName"`
	LotteryTotalMatch          int         `json:"lottery_total_match" db:"LotteryTotalMatch"`
	LotteryGameType            int         `json:"lottery_game_type" db:"LotteryGameType"`
	LotteryTotalCombination    int         `json:"lottery_total_combination" db:"LotteryTotalCombination"`
	LotteryJackpot             float64     `json:"lottery_jackpot" db:"LotteryJackpot"`
	LotteryJackpotType         string      `json:"lottery_jackpot_type" db:"LotteryJackpotType"`
	GameTypeName_BTI           null.String `json:"game_type_name_bti" db:"GameTypeName_BTI"`
	ChoiceName_BTI             null.String `json:"choice_name_bti" db:"ChoiceName_BTI"`
}
type BetEnquiryParlayCombo struct {
	Username                   string      `json:"username" db:"UserName"`
	VIPCode                    string      `json:"vip_code" db:"VIPCode"`
	BetID                      int         `json:"bet_id" db:"Bet_ID"`
	BetType                    string      `json:"bet_type" db:"Bet_Type"`
	PendingBetID               int         `json:"pending_bet_id" db:"Pending_Bet_ID"`
	BetDate                    string      `json:"bet_date" db:"Bet_Date"`
	AcceptPendingDate          string      `json:"accept_pending_date" db:"Accept_Pending_Date"`
	GameType                   int         `json:"game_type" db:"GameType"`
	BetLiveStatus              string      `json:"bet_live_status" db:"Bet_Live_Status"`
	MatchID                    int         `json:"match_id" db:"Match_ID"`
	ParlayGameType             int         `json:"parlay_game_type" db:"Parlay_GameType"`
	LeagueName                 string      `json:"league_name" db:"League_Name"`
	SportName                  string      `json:"sport_name" db:"Sport_Name"`
	HomeName                   string      `json:"home_name" db:"Home_Name"`
	AwayName                   string      `json:"away_name" db:"Away_Name"`
	BetChoice                  string      `json:"bet_choice" db:"Bet_Choice"`
	Odds                       float64     `json:"odds" db:"Odds"`
	OddsType                   int         `json:"odds_type" db:"OddsType"`
	Handicap                   float64     `json:"handicap" db:"Handicap"`
	BetFavStatus               int         `json:"bet_fav_status" db:"Bet_Fav_Status"`
	BetNeutralStatus           null.String `json:"bet_neutral_status" db:"Bet_Neutral_Status"`
	BetCommision               float64     `json:"bet_commision" db:"Bet_Commision"`
	BetScoreHome               int         `json:"bet_score_home" db:"Bet_Score_Home"`
	BetScoreAway               int         `json:"bet_score_away" db:"Bet_Score_Away"`
	HTScoreStatus              null.String `json:"ht_score_status" db:"HT_Score_Status"`
	FTScoreStatus              null.String `json:"ft_score_status" db:"FT_Score_Status"`
	FGLGScoreStatus            null.String `json:"fglg_score_status" db:"FGLG_Score_Status"`
	HTHome                     null.Int    `json:"ht_home" db:"HT_Home"`
	HTAway                     null.Int    `json:"ht_away" db:"HT_Away"`
	FSHome                     null.Int    `json:"fs_home" db:"FS_Home"`
	FSAway                     null.Int    `json:"fs_away" db:"FS_Away"`
	FGTeam                     null.Int    `json:"fg_team" db:"FG_Team"`
	LGTeam                     null.Int    `json:"lg_team" db:"LG_Team"`
	Currency                   string      `json:"currency" db:"Currency"`
	BetAmount                  float64     `json:"bet_amount" db:"Bet_Amount"`
	BetAmountRMB               float64     `json:"bet_amount_rmb" db:"Bet_Amount_RMB"`
	WinLossAmount              float64     `json:"winloss_amount" db:"WinLoss_Amount"`
	WinLossAmountRMB           float64     `json:"winloss_amount_rmb" db:"WinLoss_Amount_RMB"`
	WinLossStatus              string      `json:"winloss_status" db:"WinLoss_Status"`
	VoidID                     string      `json:"void_id" db:"Void_ID"`
	VoidUser                   string      `json:"void_user" db:"Void_User"`
	VoidDesc                   string      `json:"void_desc" db:"Void_Desc"`
	IP                         string      `json:"ip" db:"IP"`
	IsRejectedBet              string      `json:"is_rejected_bet" db:"Is_Rejected_Bet"`
	IsPostedbet                string      `json:"is_posted_bet" db:"Is_Posted_Bet"`
	IsProcessedBet             string      `json:"is_processed_bet" db:"Is_Processed_Bet"`
	IsProcessedFS              string      `json:"is_processed_fs" db:"Is_Processed_FS"`
	IsProcessedHS              string      `json:"is_processed_hs" db:"Is_Processed_HS"`
	IsProcessedFGLG            string      `json:"is_processed_fglg" db:"Is_Processed_FGLG"`
	ParlayCombination          int         `json:"parlay_combination" db:"Parlay_Combination"`
	ParlayMatchVoidID          string      `json:"parlay_match_void_id" db:"Parlay_Match_Void_ID"`
	ParlayMatchVoidDescription string      `json:"parlay_match_void_description" db:"Parlay_Match_Void_Desc"`
	ParlayMatchWinLossStatus   string      `json:"parlay_match_winloss_status" db:"Parlay_Match_WinLoss_Status"`
	BetLoss                    float64     `json:"bet_loss" db:"Bet_Loss"`
	JWL                        float64     `json:"jwl" db:"JWL"`
	OutrightTeamWinner         string      `json:"outright_team_winner" db:"Outright_Team_Winner"`
	Folds                      int         `json:"folds" db:"Folds"`
	Tickets                    int         `json:"tickets" db:"Tickets"`
	TotalOdds                  float64     `json:"total_odds" db:"TotalOdds"`
}
type BetEnquiryLottery struct {
	JackpotID  int     `json:"jackpot_id" db:"JpID"`
	LotteryID  int     `json:"lottery_id" db:"LotteryID"`
	MatchID    int     `json:"match_id" db:"No_Partai"`
	LeagueName string  `json:"league_name" db:"League"`
	HomeName   string  `json:"home_name" db:"Home"`
	AwayName   string  `json:"away_name" db:"Away"`
	GameType   int     `json:"game_type" db:"GameType"`
	Handicap   float64 `json:"handicap" db:"Handicap"`
	Choice     string  `json:"choice" db:"Choice"`
}

type BetEnquiryResult struct {
	JackpotID      int    `json:"jackpot_id" db:"JackPotID"`
	LotteryID      int    `json:"lottery_id" db:"LotteryID"`
	MatchID        int    `json:"match_id" db:"No_Partai"`
	GameType       int    `json:"game_type" db:"GameType"`
	SportID        int    `json:"sport_id" db:"SportID"`
	HomeName       string `json:"home_name" db:"HomeName"`
	AwayName       string `json:"away_name" db:"AwayName"`
	HTHome         int    `json:"ht_home" db:"HT_Home"`
	HtAway         int    `json:"ht_away" db:"HT_Away"`
	FSHome         int    `json:"fs_home" db:"FS_Home"`
	FSAway         int    `json:"fs_away" db:"FS_Away"`
	FGTeam         int    `json:"fg_team" db:"FG_Team"`
	LGTeam         int    `json:"lg_team" db:"LG_Team"`
	Selection      string `json:"selection" db:"Selection"`
	Home1          int    `json:"home1" db:"Home1"`
	Away1          int    `json:"away1" db:"Away1"`
	Home2          int    `json:"home2" db:"Home2"`
	Away2          int    `json:"away2" db:"Away2"`
	Home3          int    `json:"home3" db:"Home3"`
	Away3          int    `json:"away3" db:"Away3"`
	Home4          int    `json:"home4" db:"Home4"`
	Away4          int    `json:"away4" db:"Away4"`
	Home5          int    `json:"home5" db:"Home5"`
	Away5          int    `json:"away5" db:"Away5"`
	Home6          int    `json:"home6" db:"Home6"`
	Away6          int    `json:"away6" db:"Away6"`
	Color          int    `json:"color" db:"Color"`
	HTHomeResult   int    `json:"ht_home_result" db:"HT_Home_Result"`
	HTAwayResult   int    `json:"ht_away_result" db:"HT_Away_Result"`
	FSHomeResult   int    `json:"fs_home_result" db:"FS_Home_Result"`
	FSAwayResult   int    `json:"fs_away_result" db:"FS_Away_Result"`
	HTScoreStatus  string `json:"ht_score_status" db:"HT_Score_Status"`
	FTScoreStatus  string `json:"ft_score_status" db:"FT_Score_Status"`
	BTIResultScore string `json:"bti_result_score" db:"BTI_Result_Score"`
}

type BetEnquiryResultBetBuilder struct {
	MarketName string `json:"market_name"`
	Result     string `json:"result"`
}

type BetEnquiryExport struct {
	Username                   string      `json:"username" db:"UserName"`
	VIPCode                    string      `json:"vip_code" db:"VIPCode"`
	BetID                      int         `json:"bet_id" db:"Bet_ID"`
	BetType                    string      `json:"bet_type" db:"Bet_Type"`
	PendingBetID               int         `json:"pending_bet_id" db:"Pending_Bet_ID"`
	BetDate                    string      `json:"bet_date" db:"Bet_Date"`
	AcceptPendingDate          string      `json:"accept_pending_date" db:"Accept_Pending_Date"`
	GameType                   int         `json:"game_type" db:"GameType"`
	BetLiveStatus              string      `json:"bet_live_status" db:"Bet_Live_Status"`
	MatchID                    int         `json:"match_id" db:"Match_ID"`
	ParlayGameType             int         `json:"parlay_game_type" db:"Parlay_GameType"`
	LeagueName                 string      `json:"league_name" db:"League_Name"`
	SportName                  string      `json:"sport_name" db:"Sport_Name"`
	HomeName                   string      `json:"home_name" db:"Home_Name"`
	AwayName                   string      `json:"away_name" db:"Away_Name"`
	BetChoice                  string      `json:"bet_choice" db:"Bet_Choice"`
	Odds                       float64     `json:"odds" db:"Odds"`
	OddsType                   int         `json:"odds_type" db:"OddsType"`
	Handicap                   float64     `json:"handicap" db:"Handicap"`
	BetFavStatus               int         `json:"bet_fav_status" db:"Bet_Fav_Status"`
	BetNeutralStatus           null.String `json:"bet_neutral_status" db:"Bet_Neutral_Status"`
	BetCommision               float64     `json:"bet_commision" db:"Bet_Commision"`
	BetScoreHome               int         `json:"bet_score_home" db:"Bet_Score_Home"`
	BetScoreAway               int         `json:"bet_score_away" db:"Bet_Score_Away"`
	HTScoreStatus              null.String `json:"ht_score_status" db:"HT_Score_Status"`
	FTScoreStatus              null.String `json:"ft_score_status" db:"FT_Score_Status"`
	FGLGScoreStatus            null.String `json:"fglg_score_status" db:"FGLG_Score_Status"`
	HTHome                     null.Int    `json:"ht_home" db:"HT_Home"`
	HTAway                     null.Int    `json:"ht_away" db:"HT_Away"`
	FSHome                     null.Int    `json:"fs_home" db:"FS_Home"`
	FSAway                     null.Int    `json:"fs_away" db:"FS_Away"`
	FGTeam                     null.Int    `json:"fg_team" db:"FG_Team"`
	LGTeam                     null.Int    `json:"lg_team" db:"LG_Team"`
	Currency                   string      `json:"currency" db:"Currency"`
	BetAmount                  float64     `json:"bet_amount" db:"Bet_Amount"`
	BetAmountRMB               float64     `json:"bet_amount_rmb" db:"Bet_Amount_RMB"`
	WinLossAmount              float64     `json:"winloss_amount" db:"WinLoss_Amount"`
	WinLossAmountRMB           float64     `json:"winloss_amount_rmb" db:"WinLoss_Amount_RMB"`
	WinLossStatus              string      `json:"winloss_status" db:"WinLoss_Status"`
	VoidID                     string      `json:"void_id" db:"Void_ID"`
	VoidUser                   string      `json:"void_user" db:"Void_User"`
	VoidDesc                   string      `json:"void_desc" db:"Void_Desc"`
	IP                         string      `json:"ip" db:"IP"`
	IsRejectedBet              string      `json:"is_rejected_bet" db:"Is_Rejected_Bet"`
	IsPostedbet                string      `json:"is_posted_bet" db:"Is_Posted_Bet"`
	IsProcessedBet             string      `json:"is_processed_bet" db:"Is_Processed_Bet"`
	IsProcessedFS              string      `json:"is_processed_fs" db:"Is_Processed_FS"`
	IsProcessedHS              string      `json:"is_processed_hs" db:"Is_Processed_HS"`
	IsProcessedFGLG            string      `json:"is_processed_fglg" db:"Is_Processed_FGLG"`
	ParlayCombination          int         `json:"parlay_combination" db:"Parlay_Combination"`
	ParlayMatchVoidID          string      `json:"parlay_match_void_id" db:"Parlay_Match_Void_ID"`
	ParlayMatchVoidDescription string      `json:"parlay_match_void_description" db:"Parlay_Match_Void_Desc"`
	ParlayMatchWinLossStatus   string      `json:"parlay_match_winloss_status" db:"Parlay_Match_WinLoss_Status"`
	BetLoss                    float64     `json:"bet_loss" db:"Bet_Loss"`
	JWL                        float64     `json:"jwl" db:"JWL"`
	OutrightTeamWinner         string      `json:"outright_team_winner" db:"Outright_Team_Winner"`
	Folds                      int         `json:"folds" db:"Folds"`
	Tickets                    int         `json:"tickets" db:"Tickets"`
	StatusTicket               int         `json:"status_ticket" db:"StatusTicket"`
	ParlayLiveStatus           string      `json:"parlay_live_status" db:"Parlay_Live_Status"`
	UserAdminBuyBack           string      `json:"user_admin_buy_back" db:"UserAdminBuyBack"`
	Company                    null.String `json:"company" db:"Company"`
	SportID                    int         `json:"sport_id" db:"Sport_ID"`
	AOSExclude                 string      `json:"aos_exclude" db:"AOSExclude"`
	EarlySettlementID          string      `json:"early_settlement_id" db:"EarlySettlementID"`
	BetBuilderMarket           string      `json:"bet_builder_market" db:"BetBuilderMarket"`
	LotteryLeagueName          string      `json:"lottery_league_name" db:"LotteryLeagueName"`
	LotteryTotalMatch          int         `json:"lottery_total_match" db:"LotteryTotalMatch"`
	LotteryGameType            int         `json:"lottery_game_type" db:"LotteryGameType"`
	LotteryTotalCombination    int         `json:"lottery_total_combination" db:"LotteryTotalCombination"`
	LotteryJackpot             float64     `json:"lottery_jackpot" db:"LotteryJackpot"`
	LotteryJackpotType         string      `json:"lottery_jackpot_type" db:"LotteryJackpotType"`
}
