package model

import "github.com/guregu/null"

type CompanyWinloss struct {
	CustomerID     int     `json:"customer_id" db:"Customer_ID"`
	Username       string  `json:"username" db:"UserName"`
	CustomerLevel  string  `json:"customer_level" db:"Customer_Level"`
	BetAmount      float64 `json:"bet_amount" db:"Bet_Amount"`
	GrossComm      float64 `json:"gross_comm" db:"GrossComm"`
	WinMember      float64 `json:"win_member" db:"Win_Member"`
	CommAmtMember  float64 `json:"comm_amt_member" db:"Comm_Amt_Member"`
	TotalMember    float64 `json:"total_member" db:"Total_Member"`
	WinAgent       float64 `json:"win_agent" db:"Win_Agent"`
	CommAmtAgent   float64 `json:"comm_amt_agent" db:"Comm_Amt_Agent"`
	TotalAgent     float64 `json:"total_agent" db:"Total_Agent"`
	WinMA          float64 `json:"win_ma" db:"Win_MA"`
	CommAmtMA      float64 `json:"comm_amt_ma" db:"Comm_Amt_MA"`
	TotalMA        float64 `json:"total_ma" db:"Total_MA"`
	WinSMA         float64 `json:"win_sma" db:"Win_SMA"`
	CommAmtSMA     float64 `json:"comm_amt_sma" db:"Comm_Amt_SMA"`
	TotalSMA       float64 `json:"total_sma" db:"Total_SMA"`
	WinSSMA        float64 `json:"win_ssma" db:"Win_SSMA"`
	CommAmtSSMA    float64 `json:"comm_amt_ssma" db:"Comm_Amt_SSMA"`
	TotalSSMA      float64 `json:"total_ssma" db:"Total_SSMA"`
	WinCompany     float64 `json:"win_company" db:"Win_Company"`
	CommAmtCompany float64 `json:"comm_amt_company" db:"Comm_Amt_Company"`
	TotalCompany   float64 `json:"total_company" db:"Total_Company"`
	IndexNumber    int     `json:"index_number" db:"Index_Number"`
	Status7        string  `json:"status7" db:"Status7"`
}
type CompanyWinlossForeign struct {
	CompanyWinloss
	Currency string `json:"currency" db:"Currency"`
}
type CompanyWinlossDetail struct {
	Username          string      `json:"username" db:"Username"`
	BetID             int         `json:"bet_id" db:"Bet_ID"`
	PendingBetID      int         `json:"pending_bet_id" db:"Pending_Bet_ID"`
	BetType           string      `json:"bet_type" db:"Bet_Type"`
	BetDate           string      `json:"bet_date" db:"Bet_Date"`
	GameType          int         `json:"game_type" db:"GameType"`
	BetLiveStatus     string      `json:"bet_live_status" db:"Bet_Live_Status"`
	MatchID           int         `json:"match_id" db:"Match_ID"`
	ParlayGameType    int         `json:"parlay_game_type" db:"Parlay_GameType"`
	SportName         null.String `json:"sport_name" db:"Sport_Name"`
	LeagueName        null.String `json:"league_name" db:"League_Name"`
	HomeName          string      `json:"home_name" db:"Home_Name"`
	AwayName          string      `json:"away_name" db:"Away_Name"`
	BetChoice         string      `json:"bet_choice" db:"Bet_Choice"`
	Handicap          float64     `json:"handicap" db:"Handicap"`
	BetFavStatus      int         `json:"bet_fav_status" db:"Bet_Fav_Status"`
	BetNeutralStatus  null.String `json:"bet_neutral_status" db:"Bet_Neutral_Status"`
	BetCommision      int         `json:"bet_commision" db:"Bet_Commision"`
	BetScoreHome      string      `json:"bet_score_home" db:"Bet_Score_Home"`
	BetScoreAway      string      `json:"bet_score_away" db:"Bet_Score_Away"`
	HTScoreStatus     null.String `json:"ht_score_status" db:"HT_Score_Status"`
	FTScoreStatus     null.String `json:"ft_score_status" db:"FT_Score_Status"`
	Odds              float64     `json:"odds" db:"Odds"`
	OddsType          string      `json:"odds_type" db:"Odds_Status"`
	Currency          string      `json:"currency" db:"Currency"`
	BetAmount         float64     `json:"bet_amount" db:"Bet_Amount"`
	LossAmount        float64     `json:"loss_amount" db:"Loss_Amount"`
	WinLossStatus     string      `json:"win_loss_status" db:"WinLoss_Status"`
	HTHome            null.String `json:"ht_home" db:"HT_Home"`
	HTAway            null.String `json:"ht_away" db:"HT_Away"`
	FSHome            null.String `json:"fs_home" db:"FS_Home"`
	FSAway            null.String `json:"fs_away" db:"FS_Away"`
	WinMember         float64     `json:"win_member" db:"Win_Member"`
	CommAmtMember     float64     `json:"comm_amt_member" db:"Comm_Amt_Member"`
	WinAgent          float64     `json:"win_agent" db:"Win_Agent"`
	CommAmtAgent      float64     `json:"comm_amt_agent" db:"Comm_Amt_Agent"`
	ShareAgent        float64     `json:"share_agent" db:"Share_Agent"`
	WinMA             float64     `json:"win_ma" db:"Win_MA"`
	CommAmtMA         float64     `json:"comm_amt_ma" db:"Comm_Amt_MA"`
	ShareMA           float64     `json:"share_ma" db:"Share_MA"`
	WinSMA            float64     `json:"win_sma" db:"Win_SMA"`
	CommAmtSMA        float64     `json:"comm_amt_sma" db:"Comm_Amt_SMA"`
	ShareSMA          float64     `json:"share_sma" db:"Share_SMA"`
	WinSSMA           float64     `json:"win_ssma" db:"Win_SSMA"`
	CommAmtSSMA       float64     `json:"comm_amt_ssma" db:"Comm_Amt_SSMA"`
	ShareSSMA         float64     `json:"share_ssma" db:"Share_SSMA"`
	WinCompany        float64     `json:"win_company" db:"Win_Company"`
	CommAmtCompany    float64     `json:"comm_amt_company" db:"Comm_Amt_Company"`
	ShareCompany      float64     `json:"share_company" db:"Share_Company"`
	IP                string      `json:"ip" db:"IP"`
	ParlayCombination int         `json:"parlay_combination" db:"Parlay_Combination"`
	Folds             int         `json:"folds" db:"Folds"`
	Ticket            int         `json:"tickets" db:"Tickets"`
	BetBuilderMarket  string      `json:"bet_builder_market" db:"BetBuilderMarket"`
	GameTypeNameBTI   null.String `json:"game_type_name_bti" db:"GameTypeName_BTI"`
	ChoiceNameBTI     null.String `json:"choice_name_bti" db:"ChoiceName_BTI"`
}
