package model

import "github.com/guregu/null"

type ExportBetEnquiry struct {
	Username                 string      `json:"username" db:"UserName"`
	VIPCode                  string      `json:"vip_code" db:"VIPCode"`
	BetID                    string      `json:"bet_id" db:"Bet_ID"`
	BetType                  string      `json:"bet_type" db:"Bet_Type"`
	PendingBetID             string      `json:"pending_bet_id" db:"Pending_Bet_ID"`
	BetDate                  string      `json:"bet_date" db:"Bet_Date"`
	AcceptPendingDate        string      `json:"accept_pending_date" db:"Accept_Pending_Date"`
	GameType                 int         `json:"game_type" db:"GameType"`
	BetLiveStatus            string      `json:"bet_live_status" db:"Bet_Live_Status"`
	MatchID                  string      `json:"match_id" db:"Match_ID"`
	ParlayGameType           int         `json:"parlay_game_type" db:"Parlay_GameType"`
	LeagueName               string      `json:"league_name" db:"League_Name"`
	SportName                string      `json:"sport_name" db:"Sport_Name"`
	HomeName                 string      `json:"home_name" db:"Home_Name"`
	AwayName                 string      `json:"away_name" db:"Away_Name"`
	BetChoice                string      `json:"bet_choice" db:"Bet_Choice"`
	Odds                     float64     `json:"odds" db:"Odds"`
	OddsType                 int         `json:"odds_type" db:"OddsType"`
	Handicap                 float64     `json:"handicap" db:"Handicap"`
	BetFavStatus             int         `json:"bet_fav_status" db:"Bet_Fav_Status"`
	BetNeutralStatus         *string     `json:"bet_neutral_status" db:"Bet_Neutral_Status"`
	BetCommision             int         `json:"bet_commision" db:"Bet_Commision"`
	BetScoreHome             int         `json:"bet_score_home" db:"Bet_Score_Home"`
	BetScoreAway             int         `json:"bet_score_away" db:"Bet_Score_Away"`
	HTScoreStatus            *string     `json:"ht_score_status" db:"HT_Score_Status"`
	FTScoreStatus            *string     `json:"ft_score_status" db:"FT_Score_Status"`
	FGLGScoreStatus          *string     `json:"fglg_score_status" db:"FGLG_Score_Status"`
	HTHome                   int         `json:"ht_home" db:"HT_Home"`
	HTAway                   int         `json:"ht_away" db:"HT_Away"`
	FSHome                   int         `json:"fs_home" db:"FS_Home"`
	FSAway                   int         `json:"fs_away" db:"FS_Away"`
	FGTeam                   int         `json:"fg_team" db:"FG_Team"`
	LGTeam                   int         `json:"lg_team" db:"LG_Team"`
	Currency                 string      `json:"currency" db:"Currency"`
	BetAmount                float64     `json:"bet_amount" db:"Bet_Amount"`
	BetAmountRMB             float64     `json:"bet_amount_rmb" db:"Bet_Amount_RMB"`
	WinLossAmount            float64     `json:"winloss_amount" db:"WinLoss_Amount"`
	WinlossAmountRMB         float64     `json:"winloss_amount_rmb" db:"WinLoss_Amount_RMB"`
	WinLossStatus            string      `json:"winloss_status" db:"WinLoss_Status"`
	VoidID                   string      `json:"void_id" db:"Void_ID"`
	VoidUser                 string      `json:"void_user" db:"Void_User"`
	VoidDesc                 string      `json:"void_desc" db:"Void_Desc"`
	IP                       string      `json:"ip" db:"IP"`
	IsRejectedBet            string      `json:"is_rejected_bet" db:"Is_Rejected_Bet"`
	IsPostedBet              string      `json:"is_posted_bet" db:"Is_Posted_Bet"`
	IsProcessedBet           string      `json:"is_processed_bet" db:"Is_Processed_Bet"`
	IsProcessedFS            string      `json:"is_processed_fs" db:"Is_Processed_FS"`
	IsProcessedHS            string      `json:"is_processed_hs" db:"Is_Processed_HS"`
	IsProcessedFGLG          string      `json:"is_processed_fglg" db:"Is_Processed_FGLG"`
	ParlayCombination        int         `json:"parlay_combination" db:"Parlay_Combination"`
	ParlayMatchVoidID        string      `json:"parlay_match_void_id" db:"Parlay_Match_Void_ID"`
	ParlayMatchVoidDesc      string      `json:"parlay_match_void_desc" db:"Parlay_Match_Void_Desc"`
	ParlayMatchWinLossStatus string      `json:"parlay_match_winloss_status" db:"Parlay_Match_WinLoss_Status"`
	BetLoss                  float64     `json:"bet_loss" db:"Bet_Loss"`
	JWL                      float64     `json:"jwl" db:"JWL"`
	OutrightTeamWinner       string      `json:"outright_team_winner" db:"Outright_Team_Winner"`
	Folds                    string      `json:"folds" db:"Folds"`
	Tickets                  int         `json:"tickets" db:"Tickets"`
	StatusTicket             int         `json:"status_ticket" db:"StatusTicket"`
	ParlayLiveStatus         string      `json:"parlay_live_status" db:"Parlay_Live_Status"`
	UserAdminBuyBack         string      `json:"user_admin_buy_back" db:"UserAdminBuyBack"`
	Company                  *string     `json:"company" db:"Company"`
	SportID                  int         `json:"sport_id" db:"Sport_ID"`
	AOSExclude               string      `json:"aos_exclude" db:"AOSExclude"`
	EarlySettlementID        string      `json:"early_settlement_id" db:"EarlySettlementID"`
	BetBuilderMarket         string      `json:"bet_builder_market" db:"BetBuilderMarket"`
	LotteryLeagueName        string      `json:"lottery_league_name" db:"LotteryLeagueName"`
	LotteryTotalMatch        int         `json:"lottery_total_match" db:"LotteryTotalMatch"`
	LotteryGameType          int         `json:"lottery_game_type" db:"LotteryGameType"`
	LotteryTotalCombination  int         `json:"lottery_total_combination" db:"LotteryTotalCombination"`
	LoteryJackpot            float64     `json:"lottery_jackpot" db:"LotteryJackpot"`
	LotteryJackpotType       string      `json:"lottery_jackpot_type" db:"LotteryJackpotType"`
	GameTypeNameBTI          null.String `json:"game_type_name_bti" db:"GameTypeName_BTI"`
	ChoiceNameBTI            null.String `json:"choice_name_bti" db:"ChoiceName_BTI"`
}

type ReportMatchList struct {
	Sequence           string `json:"sequence" db:"Sequence"`
	MatchID            string `json:"match_id" db:"Match_ID"`
	MatchDate          string `json:"match_date" db:"Match_Date"`
	MatchCreateDate    string `json:"match_create_date" db:"Match_Create_Date"`
	ProfileID          string `json:"profile_id" db:"Profile_ID"`
	LeagueName         string `json:"league_name" db:"League_Name"`
	HomeName           string `json:"home_name" db:"Home_Name"`
	AwayName           string `json:"away_name" db:"Away_Name"`
	HTHome             int    `json:"ht_home" db:"HT_Home"`
	HTAway             int    `json:"ht_away" db:"HT_Away"`
	FSHome             int    `json:"fs_home" db:"FS_Home"`
	FSAway             int    `json:"fs_away" db:"FS_Away"`
	FGTeam             int    `json:"fg_team" db:"FG_Team"`
	LGTeam             int    `json:"lg_team" db:"LG_Team"`
	STVoidChoice       string `json:"st_void_choice" db:"ST_VoidChoice"`
	MatchOpenStatus    string `json:"match_open_status" db:"Match_Open_Status"`
	MatchLiveStatus    string `json:"match_live_status" db:"Match_Live_Status"`
	MatchHasLiveStatus string `json:"match_has_live_status" db:"Match_Has_Live_Status"`
	ProcessDate        string `json:"process_date" db:"Process_Date"`
	HTScoreStatus      string `json:"ht_score_status" db:"HT_Score_Status"`
	FTScoreStatus      string `json:"ft_score_status" db:"FT_Score_Status"`
	FGLGScoreStatus    string `json:"fglg_score_status" db:"FGLG_Score_Status"`
	IsMatchHasFGLG     string `json:"is_match_has_fglg" db:"Is_Match_Has_FGLG"`
	IsMatchHasTicket   string `json:"is_match_has_ticket" db:"Is_Match_Has_Ticket"`
	IsMatchHasParlay   string `json:"is_match_has_parlay" db:"Is_Match_Has_Parlay"`
	IsMatchConfirmed   string `json:"is_match_confirmed" db:"Is_Match_Confirmed"`
	Trader             string `json:"trader" db:"Trader"`
	AutoOdds           string `json:"auto_odds" db:"Auto_Odds"`
	Category           string `json:"category" db:"Category"`
	HTScoreDesc        string `json:"ht_score_desc" db:"HT_Score_Desc"`
	FTScoreDesc        string `json:"ft_score_desc" db:"FT_Score_Desc"`
	SportName          string `json:"sport_name" db:"SportName"`
}
