package model

type Forecast struct {
	LeagueSequence       string  `json:"league_sequence" db:"League_Sequence"`
	LeagueName           string  `json:"league_name" db:"League_Name"`
	MatchID              int     `json:"match_id" db:"Match_ID"`
	MatchLiveStatus      string  `json:"match_live_status" db:"Match_Live_Status"`
	GameType             int     `json:"game_type" db:"GameType"`
	Handicap             float64 `json:"handicap" db:"Handicap"`
	BetScoreHome         int     `json:"bet_score_home" db:"BetScoreHome"`
	BetScoreAway         int     `json:"bet_score_away" db:"BetScoreAway"`
	HomeName             string  `json:"home_name" db:"Home_Name"`
	AwayName             string  `json:"away_name" db:"Away_Name"`
	THome                float64 `json:"t_home" db:"T_Home"`
	TAway                float64 `json:"t_away" db:"T_Away"`
	TDraw                float64 `json:"t_draw" db:"T_Draw"`
	LiabHome             float64 `json:"liab_home" db:"Liab_Home"`
	LiabAway             float64 `json:"liab_away" db:"Liab_Away"`
	LiabDraw             float64 `json:"liab_draw" db:"Liab_Draw"`
	FSHome               int     `json:"fs_home" db:"FS_Home"`
	FSAway               int     `json:"fs_away" db:"FS_Away"`
	HTHome               int     `json:"ht_home" db:"HT_Home"`
	HTAway               int     `json:"ht_away" db:"HT_Away"`
	EvRound              int     `json:"ev_round" db:"EvRound"`
	Trader               string  `json:"trader" db:"Trader"`
	ProcessHSDate        *string `json:"process_hs_date" db:"Process_HS_Date"`
	ProcessDate          *string `json:"process_date" db:"ProcessDate"`
	SportID              int     `json:"sport_id" db:"Sport_ID"`
	Message              string  `json:"message" db:"Message"`
	OrderAH              *string `json:"order_ah" db:"Order_AH"`
	OrderOU              *string `json:"order_ou" db:"Order_OU"`
	LastUpdate           *string `json:"last_update" db:"Last_Update"`
	StampUser            *string `json:"stamp_user" db:"StampUser"`
	IntervalTraderInfo   int     `json:"interval_trader_info" db:"Interval_Trader_Info"`
	NGHome               int     `json:"ng_home" db:"NG_Home"`
	NGAway               int     `json:"ng_away" db:"NG_Away"`
	ForecastLine         int     `json:"forecast_line" db:"ForecastLine"`
	GHHome               int     `json:"gh_home" db:"GH_Home"`
	GHAway               int     `json:"gh_away" db:"GH_Away"`
	LeagueSequenceParent int     `json:"league_sequence_parent" db:"League_Sequence_Parent"`
	Liab4                float64 `json:"liab4" db:"Liab4"`
	Liab5                float64 `json:"liab5" db:"Liab5"`
	Liab6                float64 `json:"liab6" db:"Liab6"`
	Liab7                float64 `json:"liab7" db:"Liab7"`
	Liab8                float64 `json:"liab8" db:"Liab8"`
	Liab9                float64 `json:"liab9" db:"Liab9"`
}

type ForecastSingle struct {
	LeagueSequence     string  `json:"league_sequence" db:"League_Sequence"`
	LeagueName         string  `json:"league_name" db:"League_Name"`
	MatchID            int     `json:"match_id" db:"Match_ID"`
	MatchLiveStatus    string  `json:"match_live_status" db:"Match_Live_Status"`
	GameType           int     `json:"game_type" db:"GameType"`
	Handicap           float64 `json:"handicap" db:"Handicap"`
	BetScoreHome       int     `json:"bet_score_home" db:"BetScoreHome"`
	BetScoreAway       int     `json:"bet_score_away" db:"BetScoreAway"`
	HomeName           string  `json:"home_name" db:"Home_Name"`
	AwayName           string  `json:"away_name" db:"Away_Name"`
	THome              float64 `json:"t_home" db:"T_Home"`
	TAway              float64 `json:"t_away" db:"T_Away"`
	TDraw              float64 `json:"t_draw" db:"T_Draw"`
	LiabHome           float64 `json:"liab_home" db:"Liab_Home"`
	LiabAway           float64 `json:"liab_away" db:"Liab_Away"`
	LiabDraw           float64 `json:"liab_draw" db:"Liab_Draw"`
	FSHome             int     `json:"fs_home" db:"FS_Home"`
	FSAway             int     `json:"fs_away" db:"FS_Away"`
	HTHome             int     `json:"ht_home" db:"HT_Home"`
	HTAway             int     `json:"ht_away" db:"HT_Away"`
	EvRound            int     `json:"ev_round" db:"EvRound"`
	Trader             string  `json:"trader" db:"Trader"`
	SportID            int     `json:"sport_id" db:"Sport_ID"`
	Message            string  `json:"message" db:"Message"`
	OrderAH            *string `json:"order_ah" db:"Order_AH"`
	OrderOU            *string `json:"order_ou" db:"Order_OU"`
	LastUpdate         *string `json:"last_update" db:"Last_Update"`
	StampUser          *string `json:"stamp_user" db:"StampUser"`
	IntervalTraderInfo int     `json:"interval_trader_info" db:"Interval_Trader_Info"`
	NGHome             int     `json:"ng_home" db:"NG_Home"`
	NGAway             int     `json:"ng_away" db:"NG_Away"`
	ForecastLine       int     `json:"forecast_line" db:"ForecastLine"`
	GHHome             int     `json:"gh_home" db:"GH_Home"`
	GHAway             int     `json:"gh_away" db:"GH_Away"`
	Liab4              float64 `json:"liab4" db:"Liab4"`
	Liab5              float64 `json:"liab5" db:"Liab5"`
	Liab6              float64 `json:"liab6" db:"Liab6"`
	Liab7              float64 `json:"liab7" db:"Liab7"`
	Liab8              float64 `json:"liab8" db:"Liab8"`
	Liab9              float64 `json:"liab9" db:"Liab9"`
}
