package model

type MixParlay struct {
	SportID              int     `json:"sport_id" db:"Sport_ID"`
	SportSequence        int     `json:"sport_sequence" db:"Sport_Sequence"`
	LeagueID             int     `json:"league_id" db:"League_ID"`
	LeagueName           string  `json:"league_name" db:"League_Name"`
	LeagueSequence       int     `json:"league_sequence" db:"League_Sequence"`
	ProfileID            string  `json:"profile_id" db:"Profile_ID"`
	MatchID              int     `json:"match_id" db:"Match_ID"`
	MatchDate            string  `json:"match_date" db:"Match_Date"`
	MatchLiveStatus      string  `json:"match_live_status" db:"Match_Live_Status"`
	MatchPauseStatus     int     `json:"match_pause_status" db:"Match_Pause_Status"`
	MatchOpenStatus      string  `json:"match_open_status" db:"Match_Open_Status"`
	MatchHasLiveStatus   string  `json:"match_has_live_status" db:"Match_Has_Live_Status"`
	MatchNeutralStatus   string  `json:"match_neutral_status" db:"Match_Neutral_Status"`
	MatchSequence        string  `json:"match_sequence" db:"Match_Sequence"`
	HomeName             string  `json:"home_name" db:"Home_Name"`
	AwayName             string  `json:"away_name" db:"Away_Name"`
	SubMatchID           int     `json:"sub_match_id" db:"Sub_Match_ID"`
	SubMatchOpenStatus   string  `json:"sub_match_open_status" db:"Sub_Match_Open_Status"`
	SubMatchPauseStatus  int     `json:"sub_match_pause_status" db:"Sub_Match_Pause_Status"`
	SubMatchFavStatus    int     `json:"sub_match_fav_status" db:"Sub_Match_Fav_Status"`
	SubMatchOddsStep     int     `json:"sub_match_odds_step" db:"Sub_Match_Odds_Step"`
	SubMatchParlayStatus string  `json:"sub_match_parlay_status" db:"Sub_Match_Parlay_Status"`
	GameType             int     `json:"game_type" db:"GameType"`
	Handicap             float64 `json:"handicap" db:"Handicap"`
	OddsHome             float64 `json:"odds_home" db:"OddsHome"`
	OddsAway             float64 `json:"odds_away" db:"OddsAway"`
	OddsDraw             float64 `json:"odds_draw" db:"OddsDraw"`
	JmlHome              float64 `json:"jml_home" db:"JmlHome"`
	JmlAway              float64 `json:"jml_away" db:"JmlAway"`
	JmlDraw              float64 `json:"jml_draw" db:"JmlDraw"`
	THome                float64 `json:"t_home" db:"THome"`
	TAway                float64 `json:"t_away" db:"TAway"`
	TDraw                float64 `json:"t_draw" db:"TDraw"`
	Type                 int     `json:"type" db:"Type"`
	OddsStepMapping      int     `json:"odds_step_mapping" db:"Odds_Step_Mapping"`
	PriceAlert           int     `json:"price_alert" db:"Price_Alert"`
	PriceAlertTrader     int     `json:"price_alert_trader" db:"Price_Alert_Trader"`
	TraderGroup          string  `json:"trader_group" db:"TraderGroup"`
	TraderGroupPause     string  `json:"trader_group_pause" db:"TraderGroupPause"`
	LastChange           string  `json:"last_change" db:"LastChange"`
	ReasonPause          string  `json:"reason_pause" db:"Reason_Pause"`
	AutoOdds             int     `json:"auto_odds" db:"Auto_Odds"`
	LockShift            int     `json:"lock_shift" db:"Lock_Shift"`
	AutoPause            int     `json:"auto_pause" db:"Auto_Pause"`
	IsProfileChanged     int     `json:"is_profile_changed" db:"Is_Profile_Changed"`
	IsMatchConfirmed     string  `json:"is_match_confirmed" db:"Is_Match_Confirmed"`
	LastUpdateSecond     int     `json:"last_update_second" db:"LastUpdateSecond"`
	DisplayAdmin         int     `json:"display_admin" db:"Display_Admin"`
	SortIndex            string  `json:"sort_index" db:"SortIndex"`
}
