package model

import "github.com/shopspring/decimal"

type Deadball1X2AHOUOE struct {
	SportID             int             `json:"sport_id" db:"Sport_ID"`
	SportSequence       int             `json:"sport_sequence" db:"Sport_Sequence"`
	LeagueID            int             `json:"league_id" db:"League_ID"`
	LeagueName          string          `json:"league_name" db:"League_Name"`
	LeagueSequence      int             `json:"league_sequence" db:"League_Sequence"`
	ProfileID           string          `json:"profile_id" db:"Profile_ID"`
	MatchID             int             `json:"match_id" db:"Match_ID"`
	MatchDate           string          `json:"match_date" db:"Match_Date"`
	MatchLiveStatus     string          `json:"match_live_status" db:"Match_Live_Status"`
	MatchPauseStatus    int             `json:"match_pause_status" db:"Match_Pause_Status"`
	MatchOpenStatus     string          `json:"match_open_status" db:"Match_Open_Status"`
	MatchHasLiveStatus  string          `json:"match_has_live_status" db:"Match_Has_Live_Status"`
	MatchNeutralStatus  string          `json:"match_neutral_status" db:"Match_Neutral_Status"`
	MatchSequence       string          `json:"match_sequence" db:"Match_Sequence"`
	HomeName            string          `json:"home_name" db:"Home_Name"`
	AwayName            string          `json:"away_name" db:"Away_Name"`
	SubMatchID          int             `json:"sub_match_id" db:"Sub_Match_ID"`
	SubMatchOpenStatus  string          `json:"sub_match_open_status" db:"Sub_Match_Open_Status"`
	SubMatchPauseStatus string          `json:"sub_match_pause_status" db:"Sub_Match_Pause_Status"`
	SubMatchFavStatus   int             `json:"sub_match_fav_status" db:"Sub_Match_Fav_Status"`
	SubMatchOddsStep    int             `json:"sub_match_odds_step" db:"Sub_Match_Odds_Step"`
	GameType            int             `json:"game_type" db:"GameType"`
	Handicap            float64         `json:"handicap" db:"Handicap"`
	OddsHome            decimal.Decimal `json:"odds_home" db:"OddsHome"`
	OddsAway            decimal.Decimal `json:"odds_away" db:"OddsAway"`
	OddsDraw            decimal.Decimal `json:"odds_draw" db:"OddsDraw"`
	JmlHome             float64         `json:"jml_home" db:"JmlHome"`
	JmlAway             float64         `json:"jml_away" db:"JmlAway"`
	JmlDraw             float64         `json:"jml_draw" db:"JmlDraw"`
	THome               float64         `json:"t_home" db:"THome"`
	TAway               float64         `json:"t_away" db:"TAway"`
	TDraw               float64         `json:"t_draw" db:"TDraw"`
	Type                int             `json:"type" db:"Type"`
	OddsStepMapping     int             `json:"odds_step_mapping" db:"Odds_Step_Mapping"`
	PriceAlert          int             `json:"price_alert" db:"Price_Alert"`
	PriceAlertTrader    int             `json:"price_alert_trader" db:"Price_Alert_Trader"`
	TraderGroup         string          `json:"trader_group" db:"TraderGroup"`
	TraderGroupPause    string          `json:"trader_group_pause" db:"TraderGroupPause"`
	LastChange          string          `json:"last_change" db:"LastChange"`
	ReasonPause         string          `json:"reason_pause" db:"Reason_Pause"`
	AutoOdds            int             `json:"auto_odds" db:"Auto_Odds"`
	LockShift           int             `json:"lock_shift" db:"Lock_Shift"`
	AutoPause           int             `json:"auto_pause" db:"Auto_Pause"`
	IsProfileChanged    int             `json:"is_profile_changed" db:"Is_Profile_Changed"`
	IsMatchConfirmed    string          `json:"is_match_confirmed" db:"Is_Match_Confirmed"`
	LastUpdateSecond    int             `json:"last_update_second" db:"LastUpdateSecond"`
	SortIndex           string          `json:"sort_index" db:"SortIndex"`
}
type DeadballDCML struct {
	SportID             int     `json:"sport_id" db:"Sport_ID"`
	SportSequence       int     `json:"sport_sequence" db:"Sport_Sequence"`
	LeagueID            int     `json:"league_id" db:"League_ID"`
	LeagueName          string  `json:"league_name" db:"League_Name"`
	LeagueSequence      int     `json:"league_sequence" db:"League_Sequence"`
	ProfileID           string  `json:"profile_id" db:"Profile_ID"`
	MatchID             int     `json:"match_id" db:"Match_ID"`
	MatchDate           string  `json:"match_date" db:"Match_Date"`
	MatchPauseStatus    int     `json:"match_pause_status" db:"Match_Pause_Status"`
	MatchOpenStatus     string  `json:"match_open_status" db:"Match_Open_Status"`
	MatchSequence       string  `json:"match_sequence" db:"Match_Sequence"`
	HomeName            string  `json:"home_name" db:"Home_Name"`
	AwayName            string  `json:"away_name" db:"Away_Name"`
	SubMatchID          int     `json:"sub_match_id" db:"Sub_Match_ID"`
	SubMatchOpenStatus  string  `json:"sub_match_open_status" db:"Sub_Match_Open_Status"`
	SubMatchPauseStatus string  `json:"sub_match_pause_status" db:"Sub_Match_Pause_Status"`
	SubMatchOddsStep    int     `json:"sub_match_odds_step" db:"Sub_Match_Odds_Step"`
	GameType            int     `json:"game_type" db:"GameType"`
	OddsHome            float64 `json:"odds_home" db:"OddsHome"`
	OddsAway            float64 `json:"odds_away" db:"OddsAway"`
	OddsDraw            float64 `json:"odds_draw" db:"OddsDraw"`
	Jml1                float64 `json:"jml1" db:"Jml1"`
	Jml2                float64 `json:"jml2" db:"Jml2"`
	Jml3                int     `json:"jml3" db:"Jml3"`
	T1                  float64 `json:"t1" db:"T1"`
	T2                  float64 `json:"t2" db:"T2"`
	T3                  float64 `json:"t3" db:"T3"`
	Type                int     `json:"type" db:"Type"`
	OddsStepMapping     int     `json:"odds_step_mapping" db:"Odds_Step_Mapping"`
	PriceAlert          int     `json:"price_alert" db:"Price_Alert"`
	PriceAlertTrader    int     `json:"price_alert_trader" db:"Price_Alert_Trader"`
	TraderGroup         string  `json:"trader_group" db:"TraderGroup"`
	TraderGroupPause    string  `json:"trader_group_pause" db:"TraderGroupPause"`
	LastChange          string  `json:"last_change" db:"LastChange"`
	ReasonPause         string  `json:"reason_pause" db:"Reason_Pause"`
	AutoOdds            int     `json:"auto_odds" db:"Auto_Odds"`
	LockShift           int     `json:"lock_shift" db:"Lock_Shift"`
	AutoPause           int     `json:"auto_pause" db:"Auto_Pause"`
	IsProfileChanged    int     `json:"is_profile_changed" db:"Is_Profile_Changed"`
	LastUpdateSecond    int     `json:"last_update_second" db:"LastUpdateSecond"`
	SortIndex           string  `json:"sort_index" db:"SortIndex"`
}
type DeadballTG struct {
	SportID             int     `json:"sport_id" db:"Sport_ID"`
	SportSequence       int     `json:"sport_sequence" db:"Sport_Sequence"`
	LeagueID            int     `json:"league_id" db:"League_ID"`
	LeagueName          string  `json:"league_name" db:"League_Name"`
	LeagueSequence      int     `json:"league_sequence" db:"League_Sequence"`
	ProfileID           string  `json:"profile_id" db:"Profile_ID"`
	MatchID             int     `json:"match_id" db:"Match_ID"`
	MatchDate           string  `json:"match_date" db:"Match_Date"`
	MatchPauseStatus    int     `json:"match_pause_status" db:"Match_Pause_Status"`
	MatchOpenStatus     string  `json:"match_open_status" db:"Match_Open_Status"`
	MatchSequence       string  `json:"match_sequence" db:"Match_Sequence"`
	HomeName            string  `json:"home_name" db:"Home_Name"`
	AwayName            string  `json:"away_name" db:"Away_Name"`
	SubMatchID          int     `json:"sub_match_id" db:"Sub_Match_ID"`
	SubMatchOpenStatus  string  `json:"sub_match_open_status" db:"Sub_Match_Open_Status"`
	SubMatchPauseStatus string  `json:"sub_match_pause_status" db:"Sub_Match_Pause_Status"`
	SubMatchOddsStep    int     `json:"sub_match_odds_step" db:"Sub_Match_Odds_Step"`
	GameType            int     `json:"game_type" db:"GameType"`
	Odds1               float64 `json:"odds1" db:"Odds1"`
	Odds2               float64 `json:"odds2" db:"Odds2"`
	Odds3               float64 `json:"odds3" db:"Odds3"`
	Odds4               float64 `json:"odds4" db:"Odds4"`
	Jml1                int     `json:"jml1" db:"Jml1"`
	Jml2                int     `json:"jml2" db:"Jml2"`
	Jml3                int     `json:"jml3" db:"Jml3"`
	Jml4                int     `json:"jml4" db:"Jml4"`
	T1                  float64 `json:"t1" db:"T1"`
	T2                  float64 `json:"t2" db:"T2"`
	T3                  float64 `json:"t3" db:"T3"`
	T4                  float64 `json:"t4" db:"T4"`
	Type                int     `json:"type" db:"Type"`
	OddsStepMapping     int     `json:"odds_step_mapping" db:"Odds_Step_Mapping"`
	PriceAlert          int     `json:"price_alert" db:"Price_Alert"`
	PriceAlertTrader    int     `json:"price_alert_trader" db:"Price_Alert_Trader"`
	TraderGroup         string  `json:"trader_group" db:"TraderGroup"`
	TraderGroupPause    string  `json:"trader_group_pause" db:"TraderGroupPause"`
	LastChange          string  `json:"last_change" db:"LastChange"`
	ReasonPause         string  `json:"reason_pause" db:"Reason_Pause"`
	AutoOdds            int     `json:"auto_odds" db:"Auto_Odds"`
	LockShift           int     `json:"lock_shift" db:"Lock_Shift"`
	AutoPause           int     `json:"auto_pause" db:"Auto_Pause"`
	IsProfileChanged    int     `json:"is_profile_changed" db:"Is_Profile_Changed"`
	LastUpdateSecond    int     `json:"last_update_second" db:"LastUpdateSecond"`
	SortIndex           string  `json:"sort_index" db:"SortIndex"`
}
type DeadballCS struct {
	SportID             int     `json:"sport_id" db:"Sport_ID"`
	SportSequence       int     `json:"sport_sequence" db:"Sport_Sequence"`
	LeagueID            int     `json:"league_id" db:"League_ID"`
	LeagueName          string  `json:"league_name" db:"League_Name"`
	LeagueSequence      int     `json:"league_sequence" db:"League_Sequence"`
	ProfileID           string  `json:"profile_id" db:"Profile_ID"`
	MatchID             int     `json:"match_id" db:"Match_ID"`
	MatchDate           string  `json:"match_date" db:"Match_Date"`
	MatchPauseStatus    int     `json:"match_pause_status" db:"Match_Pause_Status"`
	MatchOpenStatus     string  `json:"match_open_status" db:"Match_Open_Status"`
	MatchSequence       string  `json:"match_sequence" db:"Match_Sequence"`
	HomeName            string  `json:"home_name" db:"Home_Name"`
	AwayName            string  `json:"away_name" db:"Away_Name"`
	SubMatchID          int     `json:"sub_match_id" db:"Sub_Match_ID"`
	SubMatchOpenStatus  string  `json:"sub_match_open_status" db:"Sub_Match_Open_Status"`
	SubMatchPauseStatus string  `json:"sub_match_pause_status" db:"Sub_Match_Pause_Status"`
	SubMatchOddsStep    int     `json:"sub_match_odds_step" db:"Sub_Match_Odds_Step"`
	GameType            int     `json:"game_type" db:"GameType"`
	Odds01              float64 `json:"odds1" db:"Odds01"`
	Odds02              float64 `json:"odds2" db:"Odds02"`
	Odds03              float64 `json:"odds3" db:"Odds03"`
	Odds04              float64 `json:"odds4" db:"Odds04"`
	Odds05              float64 `json:"odds5" db:"Odds05"`
	Odds06              float64 `json:"odds6" db:"Odds06"`
	Odds07              float64 `json:"odds7" db:"Odds07"`
	Odds08              float64 `json:"odds8" db:"Odds08"`
	Odds09              float64 `json:"odds9" db:"Odds09"`
	Odds10              float64 `json:"odds10" db:"Odds10"`
	Odds11              float64 `json:"odds11" db:"Odds11"`
	Odds12              float64 `json:"odds12" db:"Odds12"`
	Odds13              float64 `json:"odds13" db:"Odds13"`
	Odds14              float64 `json:"odds14" db:"Odds14"`
	Odds15              float64 `json:"odds15" db:"Odds15"`
	Odds16              float64 `json:"odds16" db:"Odds16"`
	Odds17              float64 `json:"odds17" db:"Odds17"`
	Odds18              float64 `json:"odds18" db:"Odds18"`
	Odds19              float64 `json:"odds19" db:"Odds19"`
	Odds20              float64 `json:"odds20" db:"Odds20"`
	Odds21              float64 `json:"odds21" db:"Odds21"`
	Odds22              float64 `json:"odds22" db:"Odds22"`
	Odds23              float64 `json:"odds23" db:"Odds23"`
	Odds24              float64 `json:"odds24" db:"Odds24"`
	Odds25              float64 `json:"odds25" db:"Odds25"`
	Odds26              float64 `json:"odds26" db:"Odds26"`
	Odds27              float64 `json:"odds27" db:"Odds27"`
	Jml1                int     `json:"jml1" db:"Jml1"`
	Jml2                int     `json:"jml2" db:"Jml2"`
	Jml3                int     `json:"jml3" db:"Jml3"`
	Jml4                int     `json:"jml4" db:"Jml4"`
	Jml5                int     `json:"jml5" db:"Jml5"`
	Jml6                int     `json:"jml6" db:"Jml6"`
	Jml7                int     `json:"jml7" db:"Jml7"`
	Jml8                int     `json:"jml8" db:"Jml8"`
	Jml9                int     `json:"jml9" db:"Jml9"`
	Jml10               int     `json:"jml10" db:"Jml10"`
	Jml11               int     `json:"jml11" db:"Jml11"`
	Jml12               int     `json:"jml12" db:"Jml12"`
	Jml13               int     `json:"jml13" db:"Jml13"`
	Jml14               int     `json:"jml14" db:"Jml14"`
	Jml15               int     `json:"jml15" db:"Jml15"`
	Jml16               int     `json:"jml16" db:"Jml16"`
	Jml17               int     `json:"jml17" db:"Jml17"`
	Jml18               int     `json:"jml18" db:"Jml18"`
	Jml19               int     `json:"jml19" db:"Jml19"`
	Jml20               int     `json:"jml20" db:"Jml20"`
	Jml21               int     `json:"jml21" db:"Jml21"`
	Jml22               int     `json:"jml22" db:"Jml22"`
	Jml23               int     `json:"jml23" db:"Jml23"`
	Jml24               int     `json:"jml24" db:"Jml24"`
	Jml25               int     `json:"jml25" db:"Jml25"`
	Jml26               int     `json:"jml26" db:"Jml26"`
	Jml27               int     `json:"jml27" db:"Jml27"`
	T1                  float64 `json:"t1" db:"T1"`
	T2                  float64 `json:"t2" db:"T2"`
	T3                  float64 `json:"t3" db:"T3"`
	T4                  float64 `json:"t4" db:"T4"`
	T5                  float64 `json:"t5" db:"T5"`
	T6                  float64 `json:"t6" db:"T6"`
	T7                  float64 `json:"t7" db:"T7"`
	T8                  float64 `json:"t8" db:"T8"`
	T9                  float64 `json:"t9" db:"T9"`
	T10                 float64 `json:"t10" db:"T10"`
	T11                 float64 `json:"t11" db:"T11"`
	T12                 float64 `json:"t12" db:"T12"`
	T13                 float64 `json:"t13" db:"T13"`
	T14                 float64 `json:"t14" db:"T14"`
	T15                 float64 `json:"t15" db:"T15"`
	T16                 float64 `json:"t16" db:"T16"`
	T17                 float64 `json:"t17" db:"T17"`
	T18                 float64 `json:"t18" db:"T18"`
	T19                 float64 `json:"t19" db:"T19"`
	T20                 float64 `json:"t20" db:"T20"`
	T21                 float64 `json:"t21" db:"T21"`
	T22                 float64 `json:"t22" db:"T22"`
	T23                 float64 `json:"t23" db:"T23"`
	T24                 float64 `json:"t24" db:"T24"`
	T25                 float64 `json:"t25" db:"T25"`
	T26                 float64 `json:"t26" db:"T26"`
	T27                 float64 `json:"t27" db:"T27"`
	Type                int     `json:"type" db:"Type"`
	OddsStepMapping     int     `json:"odds_step_mapping" db:"Odds_Step_Mapping"`
	PriceAlert          int     `json:"price_alert" db:"Price_Alert"`
	PriceAlertTrader    int     `json:"price_alert_trader" db:"Price_Alert_Trader"`
	TraderGroup         string  `json:"trader_group" db:"TraderGroup"`
	TraderGroupPause    string  `json:"trader_group_pause" db:"TraderGroupPause"`
	LastChange          string  `json:"last_change" db:"LastChange"`
	ReasonPause         string  `json:"reason_pause" db:"Reason_Pause"`
	AutoOdds            int     `json:"auto_odds" db:"Auto_Odds"`
	LockShift           int     `json:"lock_shift" db:"Lock_Shift"`
	AutoPause           int     `json:"auto_pause" db:"Auto_Pause"`
	IsProfileChanged    int     `json:"is_profile_changed" db:"Is_Profile_Changed"`
	LastUpdateSecond    int     `json:"last_update_second" db:"LastUpdateSecond"`
	SortIndex           string  `json:"sort_index" db:"SortIndex"`
}
type DeadballFGLG struct {
	SportID             int     `json:"sport_id" db:"Sport_ID"`
	SportSequence       int     `json:"sport_sequence" db:"Sport_Sequence"`
	LeagueID            int     `json:"league_id" db:"League_ID"`
	LeagueName          string  `json:"league_name" db:"League_Name"`
	LeagueSequence      int     `json:"league_sequence" db:"League_Sequence"`
	ProfileID           string  `json:"profile_id" db:"Profile_ID"`
	MatchID             int     `json:"match_id" db:"Match_ID"`
	MatchDate           string  `json:"match_date" db:"Match_Date"`
	MatchPauseStatus    int     `json:"match_pause_status" db:"Match_Pause_Status"`
	MatchOpenStatus     string  `json:"match_open_status" db:"Match_Open_Status"`
	MatchSequence       string  `json:"match_sequence" db:"Match_Sequence"`
	HomeName            string  `json:"home_name" db:"Home_Name"`
	AwayName            string  `json:"away_name" db:"Away_Name"`
	SubMatchID          int     `json:"sub_match_id" db:"Sub_Match_ID"`
	SubMatchOpenStatus  string  `json:"sub_match_open_status" db:"Sub_Match_Open_Status"`
	SubMatchPauseStatus string  `json:"sub_match_pause_status" db:"Sub_Match_Pause_Status"`
	SubMatchOddsStep    int     `json:"sub_match_odds_step" db:"Sub_Match_Odds_Step"`
	GameType            int     `json:"game_type" db:"GameType"`
	Odds1               float64 `json:"odds1" db:"Odds1"`
	Odds2               float64 `json:"odds2" db:"Odds2"`
	Odds3               float64 `json:"odds3" db:"Odds3"`
	Odds4               float64 `json:"odds4" db:"Odds4"`
	Odds5               float64 `json:"odds5" db:"Odds5"`
	Jml1                int     `json:"jml1" db:"Jml1"`
	Jml2                int     `json:"jml2" db:"Jml2"`
	Jml3                int     `json:"jml3" db:"Jml3"`
	Jml4                int     `json:"jml4" db:"Jml4"`
	Jml5                int     `json:"jml5" db:"Jml5"`
	T1                  float64 `json:"t1" db:"T1"`
	T2                  float64 `json:"t2" db:"T2"`
	T3                  float64 `json:"t3" db:"T3"`
	T4                  float64 `json:"t4" db:"T4"`
	T5                  float64 `json:"t5" db:"T5"`
	Type                int     `json:"type" db:"Type"`
	OddsStepMapping     int     `json:"odds_step_mapping" db:"Odds_Step_Mapping"`
	PriceAlert          int     `json:"price_alert" db:"Price_Alert"`
	PriceAlertTrader    int     `json:"price_alert_trader" db:"Price_Alert_Trader"`
	TraderGroup         string  `json:"trader_group" db:"TraderGroup"`
	TraderGroupPause    string  `json:"trader_group_pause" db:"TraderGroupPause"`
	LastChange          string  `json:"last_change" db:"LastChange"`
	ReasonPause         string  `json:"reason_pause" db:"Reason_Pause"`
	AutoOdds            int     `json:"auto_odds" db:"Auto_Odds"`
	LockShift           int     `json:"lock_shift" db:"Lock_Shift"`
	AutoPause           int     `json:"auto_pause" db:"Auto_Pause"`
	IsProfileChanged    int     `json:"is_profile_changed" db:"Is_Profile_Changed"`
	LastUpdateSecond    int     `json:"last_update_second" db:"LastUpdateSecond"`
	SortIndex           string  `json:"sort_index" db:"SortIndex"`
}
type DeadballHTFT struct {
	SportID             int     `json:"sport_id" db:"Sport_ID"`
	SportSequence       int     `json:"sport_sequence" db:"Sport_Sequence"`
	LeagueID            int     `json:"league_id" db:"League_ID"`
	LeagueName          string  `json:"league_name" db:"League_Name"`
	LeagueSequence      int     `json:"league_sequence" db:"League_Sequence"`
	ProfileID           string  `json:"profile_id" db:"Profile_ID"`
	MatchID             int     `json:"match_id" db:"Match_ID"`
	MatchDate           string  `json:"match_date" db:"Match_Date"`
	MatchPauseStatus    int     `json:"match_pause_status" db:"Match_Pause_Status"`
	MatchOpenStatus     string  `json:"match_open_status" db:"Match_Open_Status"`
	MatchSequence       string  `json:"match_sequence" db:"Match_Sequence"`
	HomeName            string  `json:"home_name" db:"Home_Name"`
	AwayName            string  `json:"away_name" db:"Away_Name"`
	SubMatchID          int     `json:"sub_match_id" db:"Sub_Match_ID"`
	SubMatchOpenStatus  string  `json:"sub_match_open_status" db:"Sub_Match_Open_Status"`
	SubMatchPauseStatus string  `json:"sub_match_pause_status" db:"Sub_Match_Pause_Status"`
	SubMatchOddsStep    int     `json:"sub_match_odds_step" db:"Sub_Match_Odds_Step"`
	GameType            int     `json:"game_type" db:"GameType"`
	Odds1               float64 `json:"odds1" db:"Odds1"`
	Odds2               float64 `json:"odds2" db:"Odds2"`
	Odds3               float64 `json:"odds3" db:"Odds3"`
	Odds4               float64 `json:"odds4" db:"Odds4"`
	Odds5               float64 `json:"odds5" db:"Odds5"`
	Odds6               float64 `json:"odds6" db:"Odds6"`
	Odds7               float64 `json:"odds7" db:"Odds7"`
	Odds8               float64 `json:"odds8" db:"Odds8"`
	Odds9               float64 `json:"odds9" db:"Odds9"`
	Jml1                int     `json:"jml1" db:"Jml1"`
	Jml2                int     `json:"jml2" db:"Jml2"`
	Jml3                int     `json:"jml3" db:"Jml3"`
	Jml4                int     `json:"jml4" db:"Jml4"`
	Jml5                int     `json:"jml5" db:"Jml5"`
	Jml6                int     `json:"jml6" db:"Jml6"`
	Jml7                int     `json:"jml7" db:"Jml7"`
	Jml8                int     `json:"jml8" db:"Jml8"`
	Jml9                int     `json:"jml9" db:"Jml9"`
	T1                  float64 `json:"t1" db:"T1"`
	T2                  float64 `json:"t2" db:"T2"`
	T3                  float64 `json:"t3" db:"T3"`
	T4                  float64 `json:"t4" db:"T4"`
	T5                  float64 `json:"t5" db:"T5"`
	T6                  float64 `json:"t6" db:"T6"`
	T7                  float64 `json:"t7" db:"T7"`
	T8                  float64 `json:"t8" db:"T8"`
	T9                  float64 `json:"t9" db:"T9"`
	Type                int     `json:"type" db:"Type"`
	OddsStepMapping     int     `json:"odds_step_mapping" db:"Odds_Step_Mapping"`
	PriceAlert          int     `json:"price_alert" db:"Price_Alert"`
	PriceAlertTrader    int     `json:"price_alert_trader" db:"Price_Alert_Trader"`
	TraderGroup         string  `json:"trader_group" db:"TraderGroup"`
	TraderGroupPause    string  `json:"trader_group_pause" db:"TraderGroupPause"`
	LastChange          string  `json:"last_change" db:"LastChange"`
	ReasonPause         string  `json:"reason_pause" db:"Reason_Pause"`
	AutoOdds            int     `json:"auto_odds" db:"Auto_Odds"`
	LockShift           int     `json:"lock_shift" db:"Lock_Shift"`
	AutoPause           int     `json:"auto_pause" db:"Auto_Pause"`
	IsProfileChanged    int     `json:"is_profile_changed" db:"Is_Profile_Changed"`
	LastUpdateSecond    int     `json:"last_update_second" db:"LastUpdateSecond"`
	SortIndex           string  `json:"sort_index" db:"SortIndex"`
}
type DeadballOutright struct {
	SportID             int             `json:"sport_id" db:"Sport_ID"`
	SportSequence       int             `json:"sport_sequence" db:"Sport_Sequence"`
	LeagueID            int             `json:"league_id" db:"League_ID"`
	LeagueName          string          `json:"league_name" db:"League_Name"`
	LeagueSequence      int             `json:"league_sequence" db:"League_Sequence"`
	OutrightID          int             `json:"outright_id" db:"Outright_ID"`
	MatchDate           string          `json:"match_date" db:"Outright_Date"`
	MatchOpenStatus     string          `json:"match_open_status" db:"Match_Open_Status"`
	TeamName            string          `json:"team_name" db:"Team_Name"`
	SubMatchID          int             `json:"sub_match_id" db:"Sub_Match_ID"`
	SubMatchSeq         int             `json:"sub_match_seq" db:"Sub_Match_Seq"`
	SubMatchOpenStatus  string          `json:"sub_match_open_status" db:"Sub_Match_Open_Status"`
	SubMatchPauseStatus string          `json:"sub_match_pause_status" db:"Sub_Match_Pause_Status"`
	Odds                decimal.Decimal `json:"odds" db:"Odds"`
	TJml                int             `json:"t_jml" db:"T_Jml"`
	TAmount             float64         `json:"t_amount" db:"T_Amount"`
	MaxLimit            float64         `json:"max_limit" db:"Max_Limit"`
	MinBet              float64         `json:"min_bet" db:"Min_Bet"`
	MaxBet              float64         `json:"max_bet" db:"Max_Bet"`
	PriceStep           float64         `json:"price_step" db:"Price_Step"`
	Limit_Change        float64         `json:"limit_change" db:"Limit_Change"`
	PriceAlertTrader    int             `json:"price_alert_trader" db:"Price_Alert_Trader"`
	TraderGroup         string          `json:"trader_group" db:"TraderGroup"`
	TraderGroupPause    string          `json:"trader_group_pause" db:"TraderGroupPause"`
	LastChange          string          `json:"last_change" db:"LastChange"`
	AutoOdds            int             `json:"auto_odds" db:"Auto_Odds"`
	LockShift           int             `json:"lock_shift" db:"Lock_Shift"`
	AutoPause           int             `json:"auto_pause" db:"Auto_Pause"`
	IsMatchConfirmed    string          `json:"is_match_confirmed" db:"Is_Match_Confirmed"`
}

type PausedMatches struct {
	NoPartai int `json:"no_partai" db:"No_Partai"`
}
