const actions = {
  SET_STATE: 'moOtherGameType/SET_STATE',
  CLEAN_UP: 'moOtherGameType/CLEAN_UP',
  CLEAN_UP_BASKET: 'moOtherGameType/CLEAN_UP_BASKET',

  LOAD_DATA: 'moOtherGameType/LOAD_DATA',
  LOAD_MORE_BASKETBALL: 'moOtherGameType/LOAD_MORE_BASKETBALL',
  REQUEST_SUB_MATCH_MORE: 'moOtherGameType/REQUEST_SUB_MATCH_MORE',
  RESET_SUB_MATCH_MORE: 'moOtherGameType/RESET_SUB_MATCH_MORE',
  UPDATE_MORE_GAME_TYPE: 'moOtherGameType/UPDATE_MORE_GAME_TYPE',
  UPDATE_MORE_GAME_TYPE_BASKETBALL: 'moOtherGameType/UPDATE_MORE_GAME_TYPE_BASKETBALL',
  UPDATE_MORE_STATUS_BG_ALL: 'moOtherGameType/UPDATE_MORE_STATUS_BG_ALL',
  UPDATE_MORE_STATUS_OPEN_ALL: 'moOtherGameType/UPDATE_MORE_STATUS_OPEN_ALL',
  UPDATE_MORE_STATUS_PAUSE_ALL: 'moOtherGameType/UPDATE_MORE_STATUS_PAUSE_ALL',
  UPDATE_MORE_STATUS_BG: 'moOtherGameType/UPDATE_MORE_STATUS_BG',
  UPDATE_MORE_STATUS_PARLAY: 'moOtherGameType/UPDATE_MORE_STATUS_PARLAY',
  UPDATE_MORE_STATUS_OPEN: 'moOtherGameType/UPDATE_MORE_STATUS_OPEN',
  UPDATE_MORE_STATUS_PAUSE: 'moOtherGameType/UPDATE_MORE_STATUS_PAUSE',
  CHANGE_ODDS_CSLIVE: 'moOtherGameType/CHANGE_ODDS_CSLIVE',

  // ui
  EDIT: 'moOtherGameType/EDIT',
  SET_VIEW_PARAMETER: 'moOtherGameType/SET_VIEW_PARAMETER',
}

export default actions
