const actions = {
  SET_STATE: 'match/SET_STATE',
  CLEAN_UP: 'match/CLEAN_UP',

  LOAD_SELECT: 'match/LOAD_SELECT',
  LOAD_SELECT_IN_MO: 'match/LOAD_SELECT_IN_MO',
  LOAD_SELECT_IN_BETLIST: 'match/LOAD_SELECT_IN_BETLIST',
  LOAD_SELECT_IN_INSTANTBET: 'match/LOAD_SELECT_IN_INSTANTBET',
  UPDATE_SELECT: 'match/UPDATE_SELECT',
  UPDATE_PAYLOAD: 'match/UPDATE_PAYLOAD',

  CREATE: 'match/CREATE',
  LOAD_MATCH_SEQUENCE: 'match/LOAD_MATCH_SEQUENCE',
  UPDATE_MATCH_SEQUENCE: 'match/UPDATE_MATCH_SEQUENCE',
  SWAP_MATCH_SEQUENCE: 'match/SWAP_MATCH_SEQUENCE',
}

export default actions
