const actions = {
  SET_STATE: 'moEdit/SET_STATE',
  CLEAN_UP: 'moEdit/CLEAN_UP',

  LOAD_MATCH: 'moEdit/LOAD_MATCH',
  LOAD_SPECIAL_CODE: 'moEdit/LOAD_SPECIAL_CODE',

  UPDATE_MATCH: 'moEdit/UPDATE_MATCH',
  UPDATE_PROFILE: 'moEdit/UPDATE_PROFILE',
  UPDATE_SPORTS_TICKER: 'moEdit/UPDATE_SPORTS_TICKER',
  UPDATE_SPORTS_TICKER_CS: 'moEdit/UPDATE_SPORTS_TICKER_CS',
  UPDATE_SPORTS_TICKER_OE: 'moEdit/UPDATE_SPORTS_TICKER_OE',
  UPDATE_MATCH_PARLAY: 'moEdit/UPDATE_MATCH_PARLAY',
  UPDATE_ODDS_POINT_DIFF: 'moEdit/UPDATE_ODDS_POINT_DIFF',
  UPDATE_PARLAY: 'moEdit/UPDATE_PARLAY',
  UPDATE_RBDelay: 'moEdit/UPDATE_RBDelay',
  UPDATE_LINK_ODDS: 'moEdit/UPDATE_LINK_ODDS',
  UPDATE_TIMED_MAX_BET: 'moEdit/UPDATE_TIMED_MAX_BET',
  UPDATE_MATCH_LIVE_STATUS: 'moEdit/UPDATE_MATCH_LIVE_STATUS',
  UPDATE_FIX_MARKET: 'moEdit/UPDATE_FIX_MARKET',
  UPDATE_AUTO_PROCESS_BETBAZAR: 'moEdit/UPDATE_AUTO_PROCESS_BETBAZAR',
  UPDATE_AUTO_PROCESS_IM: 'moEdit/UPDATE_AUTO_PROCESS_IM',
  UPDATE_PROFILE_GAMETYPE: 'moEdit/UPDATE_PROFILE_GAMETYPE',
  UPDATE_ET_PEN: 'moEdit/UPDATE_ET_PEN',
  ADD_PENALTY_SHOOT_OUT: 'moEdit/ADD_PENALTY_SHOOT_OUT',
  ADD_SUB_MATCH: 'moEdit/ADD_SUB_MATCH',
  DELETE_SUB_MATCH: 'moEdit/DELETE_SUB_MATCH',
  // ui
  OPEN_EDIT: 'moEdit/OPEN_EDIT',
  EDIT: 'moEdit/EDIT',
}

export default actions
