const actions = {
  SET_STATE: 'scoring-match/SET_STATE',
  CLEAN_UP: 'scoring-match/CLEAN_UP',
  CLEAN_UP_SPECIAL: 'scoring-match/CLEAN_UP_SPECIAL',

  LOAD: 'scoring-match/LOAD',
  LOAD_SPECIAL: 'scoring-match/LOAD_SPECIAL',
  LOAD_SPECIAL_BASKET: 'scoring-match/LOAD_SPECIAL_BASKET',
  SWAP: 'scoring-match/SWAP',
  SWAP_SPECIAL: 'scoring-match/SWAP_SPECIAL',

  LOAD_LEAGUE: 'scoring-match/LOAD_LEAGUE',

  UPDATE_HOME_AWAY_POSISI: 'scoring-match/UPDATE_HOME_AWAY_POSISI',
  UPDATE_SCORING_MATCH: 'scoring-match/UPDATE_SCORING_MATCH',
  UPDATE_SCORE_MAIN_ROUND: 'scoring-match/UPDATE_SCORE_ROUND',
  UPDATE_SCORING_RESET_MATCH: 'scoring-match/UPDATE_SCORING_RESET_MATCH',
  UPDATE_SCORING_MATCH_SPECIAL: 'scoring-match/UPDATE_SCORING_MATCH_SPECIAL',
  UPDATE_SCORING_MATCH_SPECIAL_BASKET: 'scoring-match/UPDATE_SCORING_MATCH_SPECIAL_BASKET',
  UPDATE_SCORING_DETAIL: 'scoring-match/UPDATE_SCORING_DETAIL',

  DELETE_SCORING_DETAIL: 'scoring-match/DELETE_SCORING_DETAIL',

  LOAD_SCORING_DETAIL_MATCH: 'scoring-match/LOAD_SCORING_DETAIL_MATCH',
}

export default actions
