const actions = {
  SET_STATE: 'im/SET_STATE',
  CLEAN_UP: 'im/CLEAN_UP',
  CLEAN_UP_MATCH_LIST: 'im/CLEAN_UP_MATCH_LIST',
  CLEAN_UP_ACTION_LOG: 'im/CLEAN_UP_ACTION_LOG',
  CLEAN_UP_MARKET: 'im/CLEAN_UP_MARKET',

  RESET_SERVICE: 'im/RESET_SERVICE',
  LOAD_MATCH_LIST: 'im/LOAD_MATCH_LIST',
  LOAD_ACTION_LOG: 'im/LOAD_ACTION_LOG',
  LOAD_MARKET: 'im/LOAD_MARKET',
}

export default actions
