export const categoryName = {
  0: 'Normal',
  3: 'World Cup',
  2: 'Olympic',
  4: 'EURO',
  5: 'COPA',
  1: 'Special - Normal',
  31: 'Special - World Cup',
  21: 'Special - Olympic',
  41: 'Special - EURO',
  51: 'Special - COPA',
}

export const platform = {
  BUY: 'Buyback',
  GDS: 'Graphyte SB++',
  GMB: 'Graphyte Mobile++',
  CDS: 'China Desktop',
  CMB: 'China Mobile',
  EZY: 'Simple',
  GCD: 'Graphyte Ch Desktop',
  GCM: 'Graphyte Ch Mobile',

  IPH: 'Mobile++',
  MOBILEPLUS: 'Mobile++',
  KIT: 'Mobile',
  MOBILE: 'Mobile',
  INT: 'Web',
  WEB: 'Web',
  WAP: 'SB++',
}

export const priceGroupName = {
  '0': 'All',
  '1': 'Major',
  '2': 'Medium',
  '3': 'Tournament',
  '-99': 'Default',
  '90': 'Minor',
}

export const listFEIcon = [
  { label: 'fe fe-activity', value: 'fe fe-activity' },
  { label: 'fe fe-airplay', value: 'fe fe-airplay' },
  { label: 'fe fe-alert-circle', value: 'fe fe-alert-circle' },
  { label: 'fe fe-alert-octagon', value: 'fe fe-alert-octagon' },
  { label: 'fe fe-alert-triangle', value: 'fe fe-alert-triangle' },
  { label: 'fe fe-align-center', value: 'fe fe-align-center' },
  { label: 'fe fe-align-justify', value: 'fe fe-align-justify' },
  { label: 'fe fe-align-left', value: 'fe fe-align-left' },
  { label: 'fe fe-align-right', value: 'fe fe-align-right' },
  { label: 'fe fe-anchor', value: 'fe fe-anchor' },
  { label: 'fe fe-aperture', value: 'fe fe-aperture' },
  { label: 'fe fe-archive', value: 'fe fe-archive' },
  { label: 'fe fe-arrow-down-circle', value: 'fe fe-arrow-down-circle' },
  { label: 'fe fe-arrow-down-left', value: 'fe fe-arrow-down-left' },
  { label: 'fe fe-arrow-down-right', value: 'fe fe-arrow-down-right' },
  { label: 'fe fe-arrow-down', value: 'fe fe-arrow-down' },
  { label: 'fe fe-arrow-left-circle', value: 'fe fe-arrow-left-circle' },
  { label: 'fe fe-arrow-left', value: 'fe fe-arrow-left' },
  { label: 'fe fe-arrow-right-circle', value: 'fe fe-arrow-right-circle' },
  { label: 'fe fe-arrow-right', value: 'fe fe-arrow-right' },
  { label: 'fe fe-arrow-up-circle', value: 'fe fe-arrow-up-circle' },
  { label: 'fe fe-arrow-up-left', value: 'fe fe-arrow-up-left' },
  { label: 'fe fe-arrow-up-right', value: 'fe fe-arrow-up-right' },
  { label: 'fe fe-arrow-up', value: 'fe fe-arrow-up' },
  { label: 'fe fe-at-sign', value: 'fe fe-at-sign' },
  { label: 'fe fe-award', value: 'fe fe-award' },
  { label: 'fe fe-bar-chart-2', value: 'fe fe-bar-chart-2' },
  { label: 'fe fe-bar-chart', value: 'fe fe-bar-chart' },
  { label: 'fe fe-battery-charging', value: 'fe fe-battery-charging' },
  { label: 'fe fe-battery', value: 'fe fe-battery' },
  { label: 'fe fe-bell-off', value: 'fe fe-bell-off' },
  { label: 'fe fe-bell', value: 'fe fe-bell' },
  { label: 'fe fe-bluetooth', value: 'fe fe-bluetooth' },
  { label: 'fe fe-bold', value: 'fe fe-bold' },
  { label: 'fe fe-book-open', value: 'fe fe-book-open' },
  { label: 'fe fe-book', value: 'fe fe-book' },
  { label: 'fe fe-bookmark', value: 'fe fe-bookmark' },
  { label: 'fe fe-box', value: 'fe fe-box' },
  { label: 'fe fe-briefcase', value: 'fe fe-briefcase' },
  { label: 'fe fe-calendar', value: 'fe fe-calendar' },
  { label: 'fe fe-camera-off', value: 'fe fe-camera-off' },
  { label: 'fe fe-camera', value: 'fe fe-camera' },
  { label: 'fe fe-cast', value: 'fe fe-cast' },
  { label: 'fe fe-check-circle', value: 'fe fe-check-circle' },
  { label: 'fe fe-check-square', value: 'fe fe-check-square' },
  { label: 'fe fe-check', value: 'fe fe-check' },
  { label: 'fe fe-chevron-down', value: 'fe fe-chevron-down' },
  { label: 'fe fe-chevron-left', value: 'fe fe-chevron-left' },
  { label: 'fe fe-chevron-right', value: 'fe fe-chevron-right' },
  { label: 'fe fe-chevron-up', value: 'fe fe-chevron-up' },
  { label: 'fe fe-chevrons-down', value: 'fe fe-chevrons-down' },
  { label: 'fe fe-chevrons-left', value: 'fe fe-chevrons-left' },
  { label: 'fe fe-chevrons-right', value: 'fe fe-chevrons-right' },
  { label: 'fe fe-chevrons-up', value: 'fe fe-chevrons-up' },
  { label: 'fe fe-chrome', value: 'fe fe-chrome' },
  { label: 'fe fe-circle', value: 'fe fe-circle' },
  { label: 'fe fe-clipboard', value: 'fe fe-clipboard' },
  { label: 'fe fe-clock', value: 'fe fe-clock' },
  { label: 'fe fe-cloud-drizzle', value: 'fe fe-cloud-drizzle' },
  { label: 'fe fe-cloud-lightning', value: 'fe fe-cloud-lightning' },
  { label: 'fe fe-cloud-off', value: 'fe fe-cloud-off' },
  { label: 'fe fe-cloud-rain', value: 'fe fe-cloud-rain' },
  { label: 'fe fe-cloud-snow', value: 'fe fe-cloud-snow' },
  { label: 'fe fe-cloud', value: 'fe fe-cloud' },
  { label: 'fe fe-code', value: 'fe fe-code' },
  { label: 'fe fe-codepen', value: 'fe fe-codepen' },
  { label: 'fe fe-codesandbox', value: 'fe fe-codesandbox' },
  { label: 'fe fe-coffee', value: 'fe fe-coffee' },
  { label: 'fe fe-columns', value: 'fe fe-columns' },
  { label: 'fe fe-command', value: 'fe fe-command' },
  { label: 'fe fe-compass', value: 'fe fe-compass' },
  { label: 'fe fe-copy', value: 'fe fe-copy' },
  { label: 'fe fe-corner-down-left', value: 'fe fe-corner-down-left' },
  { label: 'fe fe-corner-down-right', value: 'fe fe-corner-down-right' },
  { label: 'fe fe-corner-left-down', value: 'fe fe-corner-left-down' },
  { label: 'fe fe-corner-left-up', value: 'fe fe-corner-left-up' },
  { label: 'fe fe-corner-right-down', value: 'fe fe-corner-right-down' },
  { label: 'fe fe-corner-right-up', value: 'fe fe-corner-right-up' },
  { label: 'fe fe-corner-up-left', value: 'fe fe-corner-up-left' },
  { label: 'fe fe-corner-up-right', value: 'fe fe-corner-up-right' },
  { label: 'fe fe-cpu', value: 'fe fe-cpu' },
  { label: 'fe fe-credit-card', value: 'fe fe-credit-card' },
  { label: 'fe fe-crop', value: 'fe fe-crop' },
  { label: 'fe fe-crosshair', value: 'fe fe-crosshair' },
  { label: 'fe fe-database', value: 'fe fe-database' },
  { label: 'fe fe-delete', value: 'fe fe-delete' },
  { label: 'fe fe-disc', value: 'fe fe-disc' },
  { label: 'fe fe-divide-circle', value: 'fe fe-divide-circle' },
  { label: 'fe fe-divide-square', value: 'fe fe-divide-square' },
  { label: 'fe fe-divide', value: 'fe fe-divide' },
  { label: 'fe fe-dollar-sign', value: 'fe fe-dollar-sign' },
  { label: 'fe fe-download-cloud', value: 'fe fe-download-cloud' },
  { label: 'fe fe-download', value: 'fe fe-download' },
  { label: 'fe fe-dribbble', value: 'fe fe-dribbble' },
  { label: 'fe fe-droplet', value: 'fe fe-droplet' },
  { label: 'fe fe-edit-2', value: 'fe fe-edit-2' },
  { label: 'fe fe-edit-3', value: 'fe fe-edit-3' },
  { label: 'fe fe-edit', value: 'fe fe-edit' },
  { label: 'fe fe-external-link', value: 'fe fe-external-link' },
  { label: 'fe fe-eye-off', value: 'fe fe-eye-off' },
  { label: 'fe fe-eye', value: 'fe fe-eye' },
  { label: 'fe fe-facebook', value: 'fe fe-facebook' },
  { label: 'fe fe-fast-forward', value: 'fe fe-fast-forward' },
  { label: 'fe fe-feather', value: 'fe fe-feather' },
  { label: 'fe fe-figma', value: 'fe fe-figma' },
  { label: 'fe fe-file-minus', value: 'fe fe-file-minus' },
  { label: 'fe fe-file-plus', value: 'fe fe-file-plus' },
  { label: 'fe fe-file-text', value: 'fe fe-file-text' },
  { label: 'fe fe-file', value: 'fe fe-file' },
  { label: 'fe fe-film', value: 'fe fe-film' },
  { label: 'fe fe-filter', value: 'fe fe-filter' },
  { label: 'fe fe-flag', value: 'fe fe-flag' },
  { label: 'fe fe-folder-minus', value: 'fe fe-folder-minus' },
  { label: 'fe fe-folder-plus', value: 'fe fe-folder-plus' },
  { label: 'fe fe-folder', value: 'fe fe-folder' },
  { label: 'fe fe-framer', value: 'fe fe-framer' },
  { label: 'fe fe-frown', value: 'fe fe-frown' },
  { label: 'fe fe-gift', value: 'fe fe-gift' },
  { label: 'fe fe-git-branch', value: 'fe fe-git-branch' },
  { label: 'fe fe-git-commit', value: 'fe fe-git-commit' },
  { label: 'fe fe-git-merge', value: 'fe fe-git-merge' },
  { label: 'fe fe-git-pull-request', value: 'fe fe-git-pull-request' },
  { label: 'fe fe-github', value: 'fe fe-github' },
  { label: 'fe fe-gitlab', value: 'fe fe-gitlab' },
  { label: 'fe fe-globe', value: 'fe fe-globe' },
  { label: 'fe fe-grid', value: 'fe fe-grid' },
  { label: 'fe fe-hard-drive', value: 'fe fe-hard-drive' },
  { label: 'fe fe-hash', value: 'fe fe-hash' },
  { label: 'fe fe-headphones', value: 'fe fe-headphones' },
  { label: 'fe fe-heart', value: 'fe fe-heart' },
  { label: 'fe fe-help-circle', value: 'fe fe-help-circle' },
  { label: 'fe fe-hexagon', value: 'fe fe-hexagon' },
  { label: 'fe fe-home', value: 'fe fe-home' },
  { label: 'fe fe-image', value: 'fe fe-image' },
  { label: 'fe fe-inbox', value: 'fe fe-inbox' },
  { label: 'fe fe-info', value: 'fe fe-info' },
  { label: 'fe fe-instagram', value: 'fe fe-instagram' },
  { label: 'fe fe-italic', value: 'fe fe-italic' },
  { label: 'fe fe-key', value: 'fe fe-key' },
  { label: 'fe fe-layers', value: 'fe fe-layers' },
  { label: 'fe fe-layout', value: 'fe fe-layout' },
  { label: 'fe fe-life-buoy', value: 'fe fe-life-buoy' },
  { label: 'fe fe-link-2', value: 'fe fe-link-2' },
  { label: 'fe fe-link', value: 'fe fe-link' },
  { label: 'fe fe-linkedin', value: 'fe fe-linkedin' },
  { label: 'fe fe-list', value: 'fe fe-list' },
  { label: 'fe fe-loader', value: 'fe fe-loader' },
  { label: 'fe fe-lock', value: 'fe fe-lock' },
  { label: 'fe fe-log-in', value: 'fe fe-log-in' },
  { label: 'fe fe-log-out', value: 'fe fe-log-out' },
  { label: 'fe fe-mail', value: 'fe fe-mail' },
  { label: 'fe fe-map-pin', value: 'fe fe-map-pin' },
  { label: 'fe fe-map', value: 'fe fe-map' },
  { label: 'fe fe-maximize-2', value: 'fe fe-maximize-2' },
  { label: 'fe fe-maximize', value: 'fe fe-maximize' },
  { label: 'fe fe-meh', value: 'fe fe-meh' },
  { label: 'fe fe-menu', value: 'fe fe-menu' },
  { label: 'fe fe-message-circle', value: 'fe fe-message-circle' },
  { label: 'fe fe-message-square', value: 'fe fe-message-square' },
  { label: 'fe fe-mic-off', value: 'fe fe-mic-off' },
  { label: 'fe fe-mic', value: 'fe fe-mic' },
  { label: 'fe fe-minimize-2', value: 'fe fe-minimize-2' },
  { label: 'fe fe-minimize', value: 'fe fe-minimize' },
  { label: 'fe fe-minus-circle', value: 'fe fe-minus-circle' },
  { label: 'fe fe-minus-square', value: 'fe fe-minus-square' },
  { label: 'fe fe-minus', value: 'fe fe-minus' },
  { label: 'fe fe-monitor', value: 'fe fe-monitor' },
  { label: 'fe fe-moon', value: 'fe fe-moon' },
  { label: 'fe fe-more-horizontal', value: 'fe fe-more-horizontal' },
  { label: 'fe fe-more-vertical', value: 'fe fe-more-vertical' },
  { label: 'fe fe-mouse-pointer', value: 'fe fe-mouse-pointer' },
  { label: 'fe fe-move', value: 'fe fe-move' },
  { label: 'fe fe-music', value: 'fe fe-music' },
  { label: 'fe fe-navigation-2', value: 'fe fe-navigation-2' },
  { label: 'fe fe-navigation', value: 'fe fe-navigation' },
  { label: 'fe fe-octagon', value: 'fe fe-octagon' },
  { label: 'fe fe-package', value: 'fe fe-package' },
  { label: 'fe fe-paperclip', value: 'fe fe-paperclip' },
  { label: 'fe fe-pause-circle', value: 'fe fe-pause-circle' },
  { label: 'fe fe-pause', value: 'fe fe-pause' },
  { label: 'fe fe-pen-tool', value: 'fe fe-pen-tool' },
  { label: 'fe fe-percent', value: 'fe fe-percent' },
  { label: 'fe fe-phone-call', value: 'fe fe-phone-call' },
  { label: 'fe fe-phone-forwarded', value: 'fe fe-phone-forwarded' },
  { label: 'fe fe-phone-incoming', value: 'fe fe-phone-incoming' },
  { label: 'fe fe-phone-missed', value: 'fe fe-phone-missed' },
  { label: 'fe fe-phone-off', value: 'fe fe-phone-off' },
  { label: 'fe fe-phone-outgoing', value: 'fe fe-phone-outgoing' },
  { label: 'fe fe-phone', value: 'fe fe-phone' },
  { label: 'fe fe-pie-chart', value: 'fe fe-pie-chart' },
  { label: 'fe fe-play-circle', value: 'fe fe-play-circle' },
  { label: 'fe fe-play', value: 'fe fe-play' },
  { label: 'fe fe-plus-circle', value: 'fe fe-plus-circle' },
  { label: 'fe fe-plus-square', value: 'fe fe-plus-square' },
  { label: 'fe fe-plus', value: 'fe fe-plus' },
  { label: 'fe fe-pocket', value: 'fe fe-pocket' },
  { label: 'fe fe-power', value: 'fe fe-power' },
  { label: 'fe fe-printer', value: 'fe fe-printer' },
  { label: 'fe fe-radio', value: 'fe fe-radio' },
  { label: 'fe fe-refresh-ccw', value: 'fe fe-refresh-ccw' },
  { label: 'fe fe-refresh-cw', value: 'fe fe-refresh-cw' },
  { label: 'fe fe-repeat', value: 'fe fe-repeat' },
  { label: 'fe fe-rewind', value: 'fe fe-rewind' },
  { label: 'fe fe-rotate-ccw', value: 'fe fe-rotate-ccw' },
  { label: 'fe fe-rotate-cw', value: 'fe fe-rotate-cw' },
  { label: 'fe fe-rss', value: 'fe fe-rss' },
  { label: 'fe fe-save', value: 'fe fe-save' },
  { label: 'fe fe-scissors', value: 'fe fe-scissors' },
  { label: 'fe fe-search', value: 'fe fe-search' },
  { label: 'fe fe-send', value: 'fe fe-send' },
  { label: 'fe fe-server', value: 'fe fe-server' },
  { label: 'fe fe-settings', value: 'fe fe-settings' },
  { label: 'fe fe-share-2', value: 'fe fe-share-2' },
  { label: 'fe fe-share', value: 'fe fe-share' },
  { label: 'fe fe-shield-off', value: 'fe fe-shield-off' },
  { label: 'fe fe-shield', value: 'fe fe-shield' },
  { label: 'fe fe-shopping-bag', value: 'fe fe-shopping-bag' },
  { label: 'fe fe-shopping-cart', value: 'fe fe-shopping-cart' },
  { label: 'fe fe-shuffle', value: 'fe fe-shuffle' },
  { label: 'fe fe-sidebar', value: 'fe fe-sidebar' },
  { label: 'fe fe-skip-back', value: 'fe fe-skip-back' },
  { label: 'fe fe-skip-forward', value: 'fe fe-skip-forward' },
  { label: 'fe fe-slack', value: 'fe fe-slack' },
  { label: 'fe fe-slash', value: 'fe fe-slash' },
  { label: 'fe fe-sliders', value: 'fe fe-sliders' },
  { label: 'fe fe-smartphone', value: 'fe fe-smartphone' },
  { label: 'fe fe-smile', value: 'fe fe-smile' },
  { label: 'fe fe-speaker', value: 'fe fe-speaker' },
  { label: 'fe fe-square', value: 'fe fe-square' },
  { label: 'fe fe-star', value: 'fe fe-star' },
  { label: 'fe fe-stop-circle', value: 'fe fe-stop-circle' },
  { label: 'fe fe-sun', value: 'fe fe-sun' },
  { label: 'fe fe-sunrise', value: 'fe fe-sunrise' },
  { label: 'fe fe-sunset', value: 'fe fe-sunset' },
  { label: 'fe fe-table', value: 'fe fe-table' },
  { label: 'fe fe-tablet', value: 'fe fe-tablet' },
  { label: 'fe fe-tag', value: 'fe fe-tag' },
  { label: 'fe fe-target', value: 'fe fe-target' },
  { label: 'fe fe-terminal', value: 'fe fe-terminal' },
  { label: 'fe fe-thermometer', value: 'fe fe-thermometer' },
  { label: 'fe fe-thumbs-down', value: 'fe fe-thumbs-down' },
  { label: 'fe fe-thumbs-up', value: 'fe fe-thumbs-up' },
  { label: 'fe fe-toggle-left', value: 'fe fe-toggle-left' },
  { label: 'fe fe-toggle-right', value: 'fe fe-toggle-right' },
  { label: 'fe fe-tool', value: 'fe fe-tool' },
  { label: 'fe fe-trash-2', value: 'fe fe-trash-2' },
  { label: 'fe fe-trash', value: 'fe fe-trash' },
  { label: 'fe fe-trello', value: 'fe fe-trello' },
  { label: 'fe fe-trending-down', value: 'fe fe-trending-down' },
  { label: 'fe fe-trending-up', value: 'fe fe-trending-up' },
  { label: 'fe fe-triangle', value: 'fe fe-triangle' },
  { label: 'fe fe-truck', value: 'fe fe-truck' },
  { label: 'fe fe-tv', value: 'fe fe-tv' },
  { label: 'fe fe-twitch', value: 'fe fe-twitch' },
  { label: 'fe fe-twitter', value: 'fe fe-twitter' },
  { label: 'fe fe-type', value: 'fe fe-type' },
  { label: 'fe fe-umbrella', value: 'fe fe-umbrella' },
  { label: 'fe fe-underline', value: 'fe fe-underline' },
  { label: 'fe fe-unlock', value: 'fe fe-unlock' },
  { label: 'fe fe-upload-cloud', value: 'fe fe-upload-cloud' },
  { label: 'fe fe-upload', value: 'fe fe-upload' },
  { label: 'fe fe-user-check', value: 'fe fe-user-check' },
  { label: 'fe fe-user-minus', value: 'fe fe-user-minus' },
  { label: 'fe fe-user-plus', value: 'fe fe-user-plus' },
  { label: 'fe fe-user-x', value: 'fe fe-user-x' },
  { label: 'fe fe-user', value: 'fe fe-user' },
  { label: 'fe fe-users', value: 'fe fe-users' },
  { label: 'fe fe-video-off', value: 'fe fe-video-off' },
  { label: 'fe fe-video', value: 'fe fe-video' },
  { label: 'fe fe-voicemail', value: 'fe fe-voicemail' },
  { label: 'fe fe-volume-1', value: 'fe fe-volume-1' },
  { label: 'fe fe-volume-2', value: 'fe fe-volume-2' },
  { label: 'fe fe-volume-x', value: 'fe fe-volume-x' },
  { label: 'fe fe-volume', value: 'fe fe-volume' },
  { label: 'fe fe-watch', value: 'fe fe-watch' },
  { label: 'fe fe-wifi-off', value: 'fe fe-wifi-off' },
  { label: 'fe fe-wifi', value: 'fe fe-wifi' },
  { label: 'fe fe-wind', value: 'fe fe-wind' },
  { label: 'fe fe-x-circle', value: 'fe fe-x-circle' },
  { label: 'fe fe-x-octagon', value: 'fe fe-x-octagon' },
  { label: 'fe fe-x-square', value: 'fe fe-x-square' },
  { label: 'fe fe-x', value: 'fe fe-x' },
  { label: 'fe fe-youtube', value: 'fe fe-youtube' },
  { label: 'fe fe-zap-off', value: 'fe fe-zap-off' },
  { label: 'fe fe-zap', value: 'fe fe-zap' },
  { label: 'fe fe-zoom-in', value: 'fe fe-zoom-in' },
  { label: 'fe fe-zoom-out', value: 'fe fe-zoom-out' },
]
export default categoryName
