const actions = {
  SET_STATE: 'bbz/SET_STATE',
  CLEAN_UP: 'bbz/CLEAN_UP',
  CLEAN_UP_CHANNEL_MONITOR: 'bbz/CLEAN_UP_CHANNEL_MONITOR',
  CLEAN_UP_MATCH_LIST: 'bbz/CLEAN_UP_MATCH_LIST',
  CLEAN_UP_ACTION_LOG: 'bbz/CLEAN_UP_ACTION_LOG',
  CLEAN_UP_MARKET: 'bbz/CLEAN_UP_MARKET',
  CLEAN_UP_MARKET_LOG: 'bbz/CLEAN_UP_MARKET_LOG',
  CLEAN_UP_INCIDENT: 'bbz/CLEAN_UP_INCIDENT',

  RESET_SERVICE: 'bbz/RESET_SERVICE',
  LOAD_CHANNEL_MONITORING: 'bbz/LOAD_CHANNEL_MONITORING',
  LOAD_MATCH_LIST: 'bbz/LOAD_MATCH_LIST',
  LOAD_ACTION_LOG: 'bbz/LOAD_ACTION_LOG',
  LOAD_MARKET: 'bbz/LOAD_MARKET',
  LOAD_INCIDENT: 'bbz/LOAD_INCIDENT',
  LOAD_MARKET_LOG: 'bbz/LOAD_MARKET_LOG',
}

export default actions
