import { categoryName, platform, priceGroupName } from 'helper'

describe('const', () => {
  test('categoryName', () => {
    expect(categoryName[0]).toBe('Normal')
    expect(categoryName[3]).toBe('World Cup')
    expect(categoryName[2]).toBe('Olympic')
    expect(categoryName[4]).toBe('EURO')
    expect(categoryName[5]).toBe('COPA')
    expect(categoryName[1]).toBe('Special - Normal')
    expect(categoryName[31]).toBe('Special - World Cup')
    expect(categoryName[21]).toBe('Special - Olympic')
    expect(categoryName[41]).toBe('Special - EURO')
    expect(categoryName[51]).toBe('Special - COPA')
  })
  test('platform', () => {
    expect(platform.BUY).toBe('Buyback')
    expect(platform.GDS).toBe('Graphyte SB++')
    expect(platform.GMB).toBe('Graphyte Mobile++')
    expect(platform.CDS).toBe('China Desktop')
    expect(platform.CMB).toBe('China Mobile')
    expect(platform.EZY).toBe('Simple')
    expect(platform.GCD).toBe('Graphyte Ch Desktop')
    expect(platform.GCM).toBe('Graphyte Ch Mobile')
    expect(platform.IPH).toBe('Mobile++')
    expect(platform.MOBILEPLUS).toBe('Mobile++')
    expect(platform.KIT).toBe('Mobile')
    expect(platform.MOBILE).toBe('Mobile')
    expect(platform.INT).toBe('Web')
    expect(platform.WEB).toBe('Web')
    expect(platform.WAP).toBe('SB++')
  })
  test('priceGroupName', () => {
    expect(priceGroupName[0]).toBe('All')
    expect(priceGroupName[1]).toBe('Major')
    expect(priceGroupName[2]).toBe('Medium')
    expect(priceGroupName[3]).toBe('Tournament')
    expect(priceGroupName[-99]).toBe('Default')
    expect(priceGroupName[90]).toBe('Minor')
  })
})
