---
connection_string:
  connection_string_IS: "l5FaKgO-UZ4m9BJ0BkUuBm4QCxfI66nsoDkrLBni_whEaVA2ftLddr3nETcYK3ZbzKpLqQMtK1fBDfwT4BkQ--iqxyZbxtp4cXS6Ou7RqM50MUvagpQEfxABcjUyPuxp3yRA-_5eAz8M5ivv9pDyMM62sJ783y15t5lefObcfgseiw6iG0zx604="
  connection_string_IPost: "2zrW4Hn_9oqbStztfUGJD30YJUXK5dRwWVppfI59pQFErAGUcmGE91fJuQ0j7TfeZQwQJO7-1ryLh35FBfK8c6xA8U0DuLC6CIizJbnJRKinKtOChjlCFjAiQPCCOB1NkQ5Yafkfr_9RbiII348TLVW-WwZQ12MycnvccvReoVaF5z8WtyRomQOh2C7xDw=="
  connection_string_Log: "f8S_pb2tgnfYfOLLB3rOeQrAlpqMWMWGP0vMTmlQtUHy8r1MZMbSo_fcCgBmTKMEgHvoaxXOdXaKdwleiTfEbZGeF74Ni8jMepTp-j4DSgFnthM7tA1faTJByJzm_TSaY05Hwf_oiPbFlbj6Uzw_NsPuRmzyn2bQs_kd1EHv-K4nkq7rs3lAXYgzhuD9"
  connection_string_IHist: "wZWF_jMAsm9dHKDaEjRqnNpjyuMoDQltPKWEoCFpOOP9WTz1_tBfIBQHYcJvw5BbF7A6lO78ogBHcVK-ctSCY18IhT1MtbaN9krqt-HU24Psy_f_GC3S2ZVb4i9gnJpoYdHiLsniUhuqa-2VoFOs0gZkvAZpqjE5toz5uiNGx5vVhHaoysBgSbeIG5u5tA=="
  connection_string_LogHist: "l9DYeeGbMYG1n_oYg9P3BxEP6GEGxzJDOahG8zlC7iGtRNl-hEMGnVhr857KO1FpZXdzrhzmYLQIBSoTY7sP-sGLAGSiV5XRUH0To2C7LAshPeFmoypO8udpYO7JMEDFnxU_iDZGfoe_K0DXnsKvJqoqviONW-3c_S3qgaO-9hc_AlVWyt6GVyUPX8HAN7i_Oq4="
  connection_string_Games: "q9jgdE44mNoD0VhdklaWYdv2yViPQF_gNiafQWo3_08PfOgHD716SXn79moxRmdrOmuBDRe5T5k1h368FUrqqcK7hL8U1CmFbMWTU19SA17D1vpH_GOFC5cZPpk5qwG876K2tcINdKa6PQR6_ns8_uDQO16klb4yx-sDGL1pdGACucztad7dHQ=="
  connection_string_SUI: "Vf5OVew8dUr6SnnSZMGVUvs8qUggw7pkO9LVQkV0trBfTdy2RNMCMyf0HSamB_bkshX39RiVlEaZxwRapiFLjZda37WO_8vgx1Y7xqhsp0-QUJZIWCOzpr_YzccT0_SH2Gr6ntSxGVS4d77hiYeg1L3DgVEAEmOMALanZMWNss-jKGrG7bgibgcDdw=="
  connection_string_SB: "m4AW8GDImneRvdNxU8gmIAMwxf0a35vgjrh-lMsqTP8WK12s9mL-mYoQjAtcpXIa1H9kyzejYeK1G51RWfuX4zC3x_boPkWYwFKeaefV_uxdHpZP6C7HkO1kBH0Ls-fR3yk1k0kAmMqLt2b-HnWP6wUBUlMDZ69JivW7Hfb2fRzsnm5fvV8YaQ=="
  connection_string_GO: "XkA6R0Z1P47C6Wz9DEyJMhMrKqiaLWVzujXKaQvotGFhhCG18O0ljEPs96LNr1jhHj2Kz202xSeUMuOqcwHJp2-bbvpA7bWKPeBk17urqerQsDJfzMh0DcKHXvuwjyk_Sh_qQKNYOS2pn026YgbUF5pSqe5bqLgDVD1Xmmy3cmILR9qGJdQBo_4="
  connection_string_GO2: "rLPQsbQYvYbyukqr0inazxze44k4LqO9H17ff6HlniwXaBoHRamcpQi_wGV1ZgadqkaDMJYgMYNPC5VDcAfb44MkInSHCKNnb4tgLDj8OwygspYyuJfcYYNqTjFu39o_hwDXdPOf4GCuSY_nTakTHgnlmAXmSVQu7Nn3CkDQs_tbsY7pSH_7-cM="
  connection_string_RB: "6-I0oEdsvLq19Na-m7uk92K_S_DDtwldRE4EiZov_hk4VtsxLSI6mQZD41XfWtf6LPFph6JnuhbRl8b_UWPrR3R4VqQLCT8yNxHvddb5vMCzP6GieoanATMcKMksQK3xm_MVh0LHThCX05olVbu2ZcZ7xCfUQ2DCoD0zLNhqh0KYSEdw4kIlsu9q"
  connection_string_BG: "FW0AgRRv3J5Ck3Uzf5LA2oL7YeAaEOmLL7HaTgpTI8cNkR-R-R2NUwGPU5Nyz_KPEB2IoeEDJ2uIx2HvdwNU2uO6V25vWnUNaMeV7pwqoVnRLBM29Z8TKzT-2FdEpEheS1TtQ9hDl5rBvyZfQ1KK2OiFVU9f9H7b8G7e2Nm__UbRFaotpYmBmg=="
  connection_string_BBZ: "FHTm0l0JZJsy8cC3fG7nlEdkCc1qhzY29zpi4x-h_8WCA3YErTVIkgdJqXcAW_voI6yiyon0qW0J9KDFagMwqjUBDrNx5zCpBvYxMxHkXcBGxkFpwwjQb8eUrv6RzmM4n5jQPQxGEJHDBmw1QpKPaEHm2P0GT6tolWUqerm4wBnMr3QPTVyC"
  connection_string_RTS: "xrpOtdsF9zngWe-iH_geac_WtRPX7SCxX73OUW3W9iLYUyzAQ4G5eGXhJbA_QAOCZn3Rggp8GWfR4UI9DwUtZMcx_gUb2wZMQmmDrIMYJUkdfixgatFgQ6LpTE8qRPhBCCWUGJVxu8yVlWt3lOcZHD2rMhzijWH_8NmA20gPo7UtexgQZrC7RBl5"
  connection_string_IM: "CVsUGlil6IYF-SjBQ8TYrlUeP_xAuFQRmmvHM7SGufKTvv9ZmeysGFnbdSNrZwwceHR7g3nuk6QBkucF1HekylxAPCZZSRPy1qJU03h5R8-g-sA26khrvu5Ksg1h9BgFpxCYmADA0rP2h1jEyMjNKa-0KCG4w0_qWTTpw3_n8f0ag4jVqhj0"
  connection_string_BTI: "Pe9a966ksvlmq4DmnCie5xz58o_rNTNcl6VmK7Dt05CGYYEYKtyydjNDlYvxo9MJOdeOu6QrXEC36RUdCrpWr3hbGmp62rtpfQHNK6W2kr8hhM78tX6pVx9aZU_BZNZNf1_xp8G__dRE-LFlZOys9Ly5b8dA4Co5ug1MfwT4uQSsDz6TFEiMjg=="
  # stg
  # connection_string_IS: "mjFuFTiuZTN1Sl6kKu8ESRct1l-EOJ110L9PMNO78gO5JGror_LZv4iKQvr8cKhU3U7XRQyrU7bx58ehgaEw0jBTlXj35NTZLKdIfo1ZQe8LJVtcxMe045W2j86btFp5mymY4Z4h"
  # connection_string_IPost: "HXjcMCnu8w3oc-O5G8JL77a6AUx9DTXgcCk2sZsCrwfkmq9M9qk3yorNsASYjTxpFgufKBmxL38T08CpxOwOuGX_UbQ0SFUhpwYFvg4HHBWDBwz47BNyQQUfUo0NraMpkjpFE7-XZmLJebA="
  # connection_string_Log: "g0pkI6Y2hmKCZ09BxDn7_UoupUqkecdITHeoJqm7ylh2cUvMEL7AOIhEvxAeGd5gHpXXcRQ17QgbGRduiid1kkQApVNYEIH1HvdhL3TwWG0ocv3nZG8JoO9Y79eQzZOdV3UUzrJW_Wsg2g=="
  # connection_string_IHist: "Wg9Gkx6OPYpcJdUAM0h-PEq6p3m2r3vs5mXWccLIl0ew_ys8ToeqPOLHyCaT1VGt3TVDc9GhMg3V8baLhmQwkqig-b9X_heGtMiMxQLeyx0rOFle6PWxvQUkvTyXbSlLrb66gd0GRyIufUQ="
  # connection_string_LogHist: "gR8F2vBWvg_o3RxEJMJE0OBUEQiI1UUriG5gYg44vW0PSg-adpJENKKXEaYJaPUYpi12chpC7qbfuu1x2sDlyUzEXpAhNB8qAyv8W6eMoJuygfr8Mp01p2PHkrGi6b2bmycgyHzvOssLoI47P-Vh"
  # connection_string_Games: "MC68o0p7svyvNpQ3eYNgY_hBKGS8i2Tkep8xj03NDMu-RCTTd9gWb0yLEt0pKh7Y6EnYYRJJ0wcUsofJSabpfadR8tn_7JzKOUK0iU3QUS3seTKPdQaswDzyZwbDAYbB5mttbLc="
  # connection_string_SUI: "EMOWR3jEVCd0golNkjromjz99VXUi17zgTK1K2RBUsf1XikmJylzsZJ3pqXBnce1bVJEAuX0UcIG68_ARXT_8favCc5LIEbc7VJ6BE3a5MLwWiJqbXuTOBoSkt-UKTZORC2zVPKCUX0="
  # connection_string_SB: "OlVdOKEo5t37k4JrmQZP7UYFCsMbm-ls-16WPHiVf2g89sLNp942vl5625Q54JLCiLSQ_r6neJKJRfXs6Zv-pnNZAihWrINz0ZmXfc74sUItdGnZgYrvw6meDYs13TUtpxWjGNc="
  # connection_string_GO: "td-2KZba8YxqnQ0_LPrzbn5tL1x6z2LAltaGtkDjPyaOb_myqjlBFfKY5Mq6l-jEUorljUeBzYLEnAU7DyJB3MbBVzrK5Y5GSoVKTGiIgIPk-5vSAczQwpVCuBoDVnpRiXVQdytb"
  # connection_string_GO2: "uqiTAtdY5xydzopjP4v-DnRp2zvZzELevymAmvcMHq4u6Bh9jsCVRfpXAXhkQPyENpzC-qN7Zj9qWsR89mbNwLfNpiGWHhfiVt1zf6sKaya0iL4vgsVKB3DuyUteHfIc8iRrvqy1"
  # connection_string_RB: "sPXvAJdJE8iTgmXHPgg5LfQs_-9sKlyegS5W7NRyl5yOImWtDrUNpjAz4SyLCZYBy8BlaJ5lPOhmNKTzSVCJfTVr7LQP9FznXVizFpFIpsOwhIU4Lv3puSs1GnveEeiZOJQ6HLAYnw=="
  # connection_string_BG: "kygMCoKMqLGwxeTD-fkHBNdagvgGOX2jsYj_XO-k4wW_fyiRB2DjlyZpwbcZk0jNdMZhApMe3OIkh5p8sw-xSad2IEC6r27uUoZVBaLh7LnNZJnMGk6CokIP9DJ415bL4bjBerg="
  # connection_string_BBZ: "SNeo01PguTsF0dpdIPCcO0o21WMCTMZVbTGLXMgeOB_pXDJeBqPMwuGkc3GcR07O-rI9uJqMyjI70B5xITJwdSL6zoaXIfudEoiGFu7rZvWztBN4Ni17QwAsNKWMKshEYSryKg=="
  # connection_string_RTS: "GZPbCzuEXGgGqWb8RnjIhWsJ661Q-2i70vOwV0Ye3RDaAWBKzU77bHK2e47PT9ELtUsWTqdxIRA3bEmff5jJ39gponZMAn5wHS1xmI5eszYnlGHzT6VFfVe9XqdJUY_PX_9TJddiew=="
  # connection_string_IM: "5CnJs7k2uA3AWpCCLz0FfuUS93HGEnr_kEANkSkeWYo8ag8UJgpxSGaJRFIfcd7Bvr_w6O2ns-p1XYZY5A86Z7z4jpEGC3l4sK9ZQ4z_1tUEff_T5ovzurI0xstsScmezeQ2rQ=="
  # connection_string_BTI: "IpLr-K_DbEtG9V7HLE6k7_HWlKRX_qTQc1Z3m8bzR2ZuPtFLZANDdp-bcPugTAZKGVUNWPHIgbSZf4Ki_4zwKt8iD7Ry1Ci_BlCNsC7k163pvPphLZBy5Ch4ALB8wzUqs2MvMOc="
redis:
  enabled: true
  redis_server: 172.24.1.208:6379
  password: "000000"
  db: 0
elastic_webservice:
  reset_engine: http://api.sportbook_es.com/ResetData.ashx?SecretKey=P@$$w0rd&StampUser=SYSTEM
log_file: ""
verbose: true
schema_version: 2
bind_port: 3001
site_domain_setting:
  prefix: ""
  branch_code: ""
  operator_id: "68ED3ABC-6F1A-41F5-87D0-D64A1A0D9746"
  application_id: 8
  title: ":. SBadmin .:"
  theme: "Default"
  mail_from: "noreply@sbadmin.mansion88.com"
  mail_subject: "Welcome to SBadmin"
  mail_body: "&lt;html&gt;&lt;head&gt;&lt;title&gt;&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;p style='font-family:tahoma; font-size:8px; color:#666666;'&gt;Welcome to SBadmin, below is information of your account:&lt;br&gt;&lt;br&gt;Username : {0}&lt;br&gt;Password : {1} &lt;br&gt;&lt;br&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;"
default_password: "password123"
list_default_config_new_operator:
  [
    "ValidateSessionURL",
    "GetBalanceURL",
    "BetRequestURL",
    "CancelBetURL",
    "BetDetailURL",
    "BetRequestMixParlayURL",
    "CancelBetMixParlayURL",
    "BetDetailMixParlayURL",
    "CancelBetBBURL",
    "BetRequestBBURL",
    "BetDetailBBURL",
    "PayoutURL",
    "UnprocessURL",
  ]
operator_detail: ["89CF4994-1EDF-496F-BB1E-D3C938BD5398", "345", "M00"]
list_clear_redis_key: []
