const actions = {
  SET_STATE: 'matchList/SET_STATE',
  CLEAN_UP: 'matchList/CLEAN_UP',

  LOAD: 'matchList/LOAD',
  DELETE: 'matchList/DELETE',

  LOAD_SPECIAL_CODE: 'matchlist/LOAD_SPECIAL_CODE',
  LOAD_MATCH_EDIT: 'matchlist/LOAD_DATA_EDIT',
  UPDATE_MATCH_EDIT: 'matchlist/UPDATE_EDIT_MATCH',
  CLEAN_UP_DATA_EDIT: 'matchlist/CLEAN_UP_DATA_EDIT',

  LOAD_MATCH_INFO: 'matchList/LOAD_MATCH_INFO',
  UPDATE_MATCH_INFO: 'matchlist/UPDATE_MATCH_INFO',

  LOAD_LIST_SUB_MATCH: 'matchList/LOAD_LIST_SUB_MATCH',
  CLEAN_UP_LIST_SUB_MATCH: 'matchList/CLEAN_UP_LIST_SUB_MATCH',

  LOAD_DETAIL_SPECIAL: 'matchList/LOAD_DETAIL_SPECIAL',
  DELETE_DETAIL_SPECIAL: 'matchList/DELETE_DETAIL_SPECIAL',
  CLEAN_UP_DETAIL_SPECIAL: 'matchList/CLEAN_UP_DETAIL_SPECIAL',

  LOAD_MATCH_SPECIAL: 'matchList/LOAD_SPECIAL_MATCH',
  UPDATE_MATCH_SPECIAL: 'matchList/UPDATE_SPECIAL_MATCH',
  CLEAN_UP_MATCH_SPECIAL: 'matchList/CLEAN_UP_SPECIAL_MATCH',
  LOAD_MATCH_SPECIAL_MORE: 'matchList/LOAD_SPECIAL_MORE',
  UPDATE_MATCH_SPECIAL_MORE: 'matchlist/UPDATE_SPECIAL_MORE',
  CLEAN_UP_MATCH_SPECIAL_MORE: 'matchlist/CLEAN_UP_SPECIAL_MORE',
}

export default actions
