const actions = {
  SET_STATE: 'outright/SET_STATE',
  CLEAN_UP: 'outright/CLEAN_UP',
  CLEAN_UP_LIST: 'outright/CLEAN_UP_LIST',

  CREATE_OUTRIGHT: 'outright/CREATE_OUTRIGHT',

  LOAD_OUTRIGHT: 'outright/LOAD_OUTRIGHT',
  LOAD_OUTRIGHT_TEAM: 'outright/LOAD_OUTRIGHT_TEAM',
  LOAD_EDIT_OUTRIGHT: 'outright/LOAD_EDIT_OUTRIGHT',
  UPDATE_EDIT_OUTRIGHT: 'outright/UPDATE_EDIT_OUTRIGHT',
  DELETE_OUTRIGHT: 'outright/DELETE_OUTRIGHT',
}

export default actions
