const actions = {
  SET_STATE: 'trading-floor/SET_STATE',
  CLEAN_UP: 'trading-floor/CLEAN_UP',

  UPDATE_MATCH_MORE_GT: 'trading-floor/UPDATE_MATCH_MORE_GT',

  UPDATE_OPEN_CLOSE_MATCH: 'trading-floor/UPDATE_OPEN_CLOSE_MATCH',
  UPDATE_PAUSE_RESUME_MATCH: 'trading-floor/UPDATE_PAUSE_RESUME_MATCH',
  UPDATE_OPEN_CLOSE_SUB_MATCH: 'trading-floor/UPDATE_OPEN_CLOSE_SUB_MATCH',
  UPDATE_PAUSE_RESUME_SUB_MATCH: 'trading-floor/UPDATE_PAUSE_RESUME_SUB_MATCH',

  UPDATE_LIVE_FINALIZE: 'trading-floor/UPDATE_LIVE_FINALIZE',
  UPDATE_ODDS_HDC: 'trading-floor/UPDATE_ODDS_HDC',
  UPDATE_TRADING_MOVE_ODDS: 'trading-floor/UPDATE_TRADING_MOVE_ODDS',

  UPDATE_OPEN_CLOSE_SUB_MATCH_OUTRIGHT: 'trading-floor/UPDATE_OPEN_CLOSE_SUB_MATCH_OUTRIGHT',
  UPDATE_PAUSE_RESUME_SUB_MATCH_OUTRIGHT: 'trading-floor/UPDATE_PAUSE_RESUME_SUB_MATCH_OUTRIGHT',
  UPDATE_OPEN_CLOSE_OUTRIGHT: 'trading-floor/UPDATE_OPEN_CLOSE_OUTRIGHT',
  UPDATE_PAUSE_RESUME_OUTRIGHT: 'trading-floor/UPDATE_PAUSE_RESUME_OUTRIGHT',
  UPDATE_TRADING_OUTRIGHT_SETTING: 'trading-floor/UPDATE_TRADING_OUTRIGHT_SETTING',
  UPDATE_TRADING_CONFIRM_OUTRIGHT: 'trading-floor/UPDATE_TRADING_CONFIRM_OUTRIGHT',
}

export default actions
