const actions = {
  SET_STATE: 'ledger/SET_STATE',
  CLEAN_UP_HIST: 'ledger/CLEAN_UP_HIST',
  CLEAN_UP_POST: 'ledger/CLEAN_UP_POST',
  CLEAN_UP_DETAIL: 'ledger/CLEAN_UP_DETAIL',

  LOAD_LEDGER_MAIN: 'ledger/LOAD_LEDGER_MAIN',
  LOAD_LEDGER_AVG: 'ledger/LOAD_LEDGER_AVG',
  LOAD_LEDGER_NEW: 'ledger/LOAD_LEDGER_NEW',
  LOAD_LEDGER_BREAKDOWN: 'ledger/LOAD_LEDGER_BREAKDOWN',
  LOAD_LEDGER_DETAIL: 'ledger/LOAD_LEDGER_DETAIL',

  EXPORT_DETAIL: 'ledger/EXPORT_DETAIL',
}

export default actions
