const actions = {
  SET_STATE: 'instantBet/SET_STATE',
  CLEAN_UP: 'instantBet/CLEAN_UP',

  LOAD_LIST_PARLAY: 'instantBet/LOAD_LIST_PARLAY',
  LOAD_LIST_MATCH_PARLAY: 'instantBet/LOAD_LIST_MATCH_PARLAY',
  LOAD_LIST_LOTTERY: 'instantBet/LOAD_LIST_LOTTERY',

  UPDATE_TICKET: 'instantBet/UPDATE_TICKET',
  // SWAP_FAVOURITE: 'instantBet/SWAP_FAVOURITE',
  // UPDATE_ZERO_ODDS: 'instantBet/UPDATE_ZERO_ODDS',
  // MOVE_HANDICAP: 'instantBet/MOVE_HANDICAP',
  // CHANGE_HANDICAP: 'instantBet/CHANGE_HANDICAP',
  // SWAP_HANDICAP: 'instantBet/SWAP_HANDICAP',
  // CHANGE_ODDS: 'instantBet/CHANGE_ODDS',
  // CHANGE_ODDS_EURO: 'instantBet/CHANGE_ODDS_EURO',
  // CHANGE_ODDS_CSLIVE: 'instantBet/CHANGE_ODDS_CSLIVE',
  // CHANGE_ODDS_1X2: 'instantBet/CHANGE_ODDS_1X2',
  // SWAP_ODDS: 'instantBet/SWAP_ODDS',
  // MOVE_ODDS: 'instantBet/MOVE_ODDS',
  // CHANGE_LOD: 'instantBet/CHANGE_LOD',
  // CHANGE_SPREAD: 'instantBet/CHANGE_SPREAD',
  // CHANGE_AUTO_CALC_ODDS_1X2: 'instantBet/CHANGE_AUTO_CALC_ODDS_1X2',
  // CHANGE_LDIFF: 'instantBet/CHANGE_LDIFF',

  // PAUSE_RESUME_CHOICE: 'instantBet/PAUSE_RESUME_CHOICE',
  // PAUSE_RESUME_SUB_MATCH_CS: 'instantBet/UPDATE_PAUSE_RESUME_SUB_MATCH_CS',
  // PAUSE_RESUME_SUB_MATCH: 'instantBet/UPDATE_PAUSE_RESUME_SUB_MATCH',
  // PAUSE_RESUME_MATCH: 'instantBet/PAUSE_RESUME_MATCH',
  // PAUSE_RESUME_ALL: 'instantBet/UPDATE_PAUSE_RESUME_ALL',
  // OPEN_CLOSE_CHOICE: 'instantBet/OPEN_CLOSE_CHOICE',
  // OPEN_CLOSE_SUB_MATCH_CS: 'instantBet/OPEN_CLOSE_SUB_MATCH_CS',
  // OPEN_CLOSE_SUB_MATCH: 'instantBet/OPEN_CLOSE_SUB_MATCH',
  // OPEN_CLOSE_MATCH: 'instantBet/OPEN_CLOSE_MATCH',
  // FOLLOW_LEECH_SUB_MATCH: 'instantBet/FOLLOW_LEECH_SUB_MATCH',
  // UPDATE_LEECH_ASSIGN: 'instantBet/UPDATE_LEECH_ASSIGN',

  // ui
  SET_VIEW_PARAMETER: 'instantBet/SET_VIEW_PARAMETER',
  OPEN_INSTANT_BET_DETAIL: 'instantBet/OPEN_INSTANT_BET_DETAIL',
}

export default actions
