const actions = {
  SET_STATE: 'BTIautoAddMatch/SET_STATE',
  CLEAN_UP: 'BTIautoAddMatch/CLEAN_UP',
  CLEAR_TABLE_UNMAPPED: 'BTIautoAddMatch/CLEAR_TABLE_UNMAPPED',
  CLEAR_TABLE_MAPPED: 'BTIautoAddMatch/CLEAR_TABLE_MAPPED',

  LOAD_SELECT_LEAGUE: 'BTIautoAddMatch/LOAD_SELECT_LEAGUE',
  LOAD_UNMAPPED: 'BTIautoAddMatch/LOAD_UNMAPPED',
  LOAD_MAPPED: 'BTIautoAddMatch/LOAD_MAPPED',

  // SELECT: 'BTIautoAddMatch/SELECT',
  // SELECT_MAPPED: 'BTIautoAddMatch/SELECT_MAPPED',
  INSERT_MATCH: 'BTIautoAddMatch/INSERT_MATCH',
}

export default actions
