const actions = {
  SET_STATE: 'userTeam/SET_STATE',
  CLEAN_UP: 'userTeam/CLEAN_UP',
  PRELOAD: 'userTeam/PRELOAD',

  LOAD_USER_TEAM: 'userTeam/LOAD_USER_TEAM',
  ADD_USER_TEAM: 'userTeam/ADD_USER_TEAM',
  UPDATE_USER_TEAM: 'userTeam/UPDATE_USER_TEAM',
  DELETE_USER_TEAM: 'userTeam/DELETE_USER_TEAM',

  LOAD_USER_TEAM_SUB: 'userTeam/LOAD_USER_TEAM_SUB',
  ADD_USER_TEAM_SUB: 'userTeam/ADD_USER_TEAM_SUB',
  UPDATE_USER_TEAM_SUB: 'userTeam/UPDATE_USER_TEAM_SUB',
  DELETE_USER_TEAM_SUB: 'userTeam/DELETE_USER_TEAM_SUB',

  LOAD_MAPPING_USER: 'userTeam/LOAD_MAPPING_USER',
  UPDATE_MAPPING_USER: 'userTeam/UPDATE_MAPPING_USER',

  LOAD_MAPPING_USER_SUB: 'userTeam/LOAD_MAPPING_USER_SUB',
  UPDATE_MAPPING_USER_SUB: 'userTeam/UPDATE_MAPPING_USER_SUB',

  LOAD_LEAGUE: 'userTeam/LOAD_LEAGUE',
  UPDATE_LEAGUE: 'userTeam/UPDATE_LEAGUE',
}

export default actions
