name: Build and Deploy to DEV environment

on:
  push:
    branches:
      - development
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: asia-southeast1-a
  GKE_CLUSTER: dev-cluster
  IMAGE: tsubasa-admin
  REGISTRY_HOSTNAME: gcr.io
  DEPLOYMENT_NAME: tsubasa-admin

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Commit Message
        run: |
          echo "COMMIT_MSG=\"$(git log -1 --oneline)\"" >> $GITHUB_ENV
          
      # Setup gcloud CLI
      - uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GKE_EMAIL }}
          credentials_json: ${{ secrets.GKE_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
          
      # Build the Docker image
      - name: Build
        run: |
          docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
            
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA
          
      # Update gitops repo
      - name: Update gitops repo
        uses: actions/checkout@v2
        with:
          repository: "AxionHQ/tsubasa-config"
          token: ${{ secrets.GITOPS_PAT }}
          path: "app-deployment"

      - run: |
          cd app-deployment/development/tsubasa-admin
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          ./kustomize edit set image $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${GITHUB_SHA}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$COMMIT_MSG"
          git push
