name: Build and Deploy to Production environment

on:
  push:
    branches:
      - stable
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: sb2
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: tsubasa-admin
  REGISTRY_HOSTNAME: reg.s3dv.io
  DEPLOYMENT_NAME: tsubasa-admin

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Commit Message
        run: |
          echo "COMMIT_MSG=\"$(git log -1 --pretty=%b)\"" >> $GITHUB_ENV
      # Configure docker
      - run: |
          # Set up docker to authenticate
          echo "${{ secrets.S3DV_REG_TOKEN }}" | docker login $REGISTRY_HOSTNAME -u "${{ secrets.S3DV_REG_ID }}" --password-stdin

      # Build the Docker image
      - name: Build
        run: |
          docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
      # Push the Docker image to Private Container Registry
      - name: Publish Docker Image
        run: |
          docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA

      # Set up kustomize
      - name: Set up Kustomize
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          curl -o $GITHUB_WORKSPACE/bin/kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x $GITHUB_WORKSPACE/bin/kustomize
      # Deploy the Docker image to the ARGOCD
      - name: Checkout gitops repo
        uses: actions/checkout@v2
        with:
          repository: "AxionHQ/tsubasa-config"
          token: ${{ secrets.GITOPS_PAT }}
          path: "app-deployment"

      - name: Update Production ENV gitops repo
        run: |
          cd app-deployment/production/tsubasa-admin
          kustomize edit set image $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${GITHUB_SHA}
      - name: Commit gitops repo
        run: |
          cd app-deployment
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$COMMIT_MSG"
          git push
